In [7]:
#setup notebook
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib notebook
#%autosave 0
import base64
import pandas as pd
import numpy as np
import uuid
import os
import sys
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.WARNING, datefmt='%I:%M:%S')

import sdata
from sdata import SUUID
from sdata.base import Base, sdata_factory, sclass_factory

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
project = SUUID.from_name(class_name="Project", name="MyProject", ns_name="")
project

In [13]:
b = Base(class_name="Myclass", name="Otto I.")
b.md.add("fill_time", value=1.2, unit="s", label="Füllzeit")
b.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base.Base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-11-11T14:22:36.939724+00:00,-,str,UTC creation date,,True,
_sdata_name,_sdata_name,Otto I.,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__otto_i__f3df2631a4f1424ea21eca6440657578,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,
fill_time,fill_time,1.2,s,float,,Füllzeit,False,

In [14]:
print(b.to_json())

{
    "metadata": {
        "_sdata_class": {
            "name": "_sdata_class",
            "value": "sdata.base.Base:Base",
            "unit": "-",
            "dtype": "str",
            "description": "sdata class",
            "label": "",
            "required": true,
            "ontology": ""
        },
        "_sdata_ctime": {
            "name": "_sdata_ctime",
            "value": "2025-11-11T14:22:36.939724+00:00",
            "unit": "-",
            "dtype": "str",
            "description": "UTC creation date",
            "label": "",
            "required": true,
            "ontology": ""
        },
        "_sdata_name": {
            "name": "_sdata_name",
            "value": "Otto I.",
            "unit": "-",
            "dtype": "str",
            "description": "name of the data object",
            "label": "",
            "required": true,
            "ontology": ""
        },
        "_sdata_parent_sname": {
            "name": "_sdata_parent_sname",
            "value": "",
            "unit": "-",
            "dtype": "str",
            "description": "sname of the parent",
            "label": "",
            "required": false,
            "ontology": ""
        },
        "_sdata_project_sname": {
            "name": "_sdata_project_sname",
            "value": "",
            "unit": "-",
            "dtype": "str",
            "description": "sname of the project",
            "label": "",
            "required": false,
            "ontology": ""
        },
        "_sdata_sname": {
            "name": "_sdata_sname",
            "value": "Base__otto_i__f3df2631a4f1424ea21eca6440657578",
            "unit": "-",
            "dtype": "str",
            "description": "sname of the data object",
            "label": "",
            "required": true,
            "ontology": ""
        },
        "_sdata_topology_class": {
            "name": "_sdata_topology_class",
            "value": "sdata.sclass:IndependentContinuant",
            "unit": "-",
            "dtype": "str",
            "description": "sdata topology class name",
            "label": "",
            "required": false,
            "ontology": ""
        },
        "_sdata_version": {
            "name": "_sdata_version",
            "value": "1.0.0",
            "unit": "-",
            "dtype": "str",
            "description": "sdata package version",
            "label": "",
            "required": true,
            "ontology": ""
        },
        "fill_time": {
            "name": "fill_time",
            "value": 1.2,
            "unit": "s",
            "dtype": "float",
            "description": "",
            "label": "F\u00fcllzeit",
            "required": false,
            "ontology": ""
        }
    },
    "data": {},
    "description": ""
}

In [104]:
from sdata.sclass.process import sclass, pdata
pdata("PartOpt")(project="dp2g", parent="SS").mdf

06:11:43 WARNING:invalid project sname 'dp2g'
06:11:43 WARNING:invalid parent sname 'SS'

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.process:PartOpt,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T18:11:43.577684+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,PartOpt__noname__62d5d35e59f645d996996fb1bed5fada,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:GenericallyDependentContinuant,-,str,sdata bfo class name,,True,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [107]:
from sdata.sclass.process import sclass, pdata
po=pdata("PartOpt")(name="A", project=project, parent="PartOpt__noname__14a79c20a6a44100b0a8a3479c7f61ee")
po

In [110]:
po.parent.sname

'PartOpt__noname__14a79c20a6a44100b0a8a3479c7f61ee'

In [99]:
p = Base(name="papa", project=project)
p

In [100]:
from sdata.sclass.process import sclass, pdata
pdata("PartOpt")(project="dp2g",parent=p).mdf

06:11:34 WARNING:invalid project sname 'dp2g'

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.process:PartOpt,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T18:11:34.041660+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,Base__papa__a59503d5ca1a5f31a1c8dc8bf4e7d3c0,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,PartOpt__noname__a034a03ccb064e859fb81e972d1bd105,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:GenericallyDependentContinuant,-,str,sdata bfo class name,,True,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [101]:
SUUID.from_suuid_sname("MyData__otto__5f38dc0e6d964cc3ae62805bc4911c05")

(suuid:MyData__otto__5f38dc0e6d964cc3ae62805bc4911c05)

In [43]:
b = Base(class_name="Myclass", name="otto", project="Project__otto__5f38dc0e6d964cc3ae62805bc4913c05", parent=p)
b.mdf

parent_sname! Base__papa__f711d51db6ec4d94b83f2c29aaa2963e

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T17:39:15.182706+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,otto,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,Base__papa__f711d51db6ec4d94b83f2c29aaa2963e,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__otto__5f38dc0e6d964cc3ae62805bc4913c05,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__otto__55852daa82c9573face1af7134fb0955,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [44]:
b = Base(class_name="Myclass", name="otto", project="Project__otto__5f38dc0e6d964cc3ae62805bc4913c05", parent="MyData__otto__5f38dc0e6d964cc3ae62805bc4911c05")
b.mdf

parent_sname! MyData__otto__5f38dc0e6d964cc3ae62805bc4911c05

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T17:39:37.764256+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,otto,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,MyData__otto__5f38dc0e6d964cc3ae62805bc4911c05,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__otto__5f38dc0e6d964cc3ae62805bc4913c05,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__otto__55852daa82c9573face1af7134fb0955,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

(Project__myproject__f3128481a3c854f8a9b35543788ac3a9)

In [25]:
b = Base(name="test")
b

05:35:46 WARNING:'NoneType' object has no attribute 'split'

In [26]:
b = Base(name="test", project="digipro2green")
b.sdf

05:35:47 WARNING:Ungültiger sname-Format: Muss genau zwei Separatoren enthalten
05:35:47 WARNING:'NoneType' object has no attribute 'split'

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T17:35:47.064058+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,test,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__test__57d2e002fb4945c39792110b3b20c3ed,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [27]:
project = SUUID.from_obj("MyProject", class_name="Project")
b = Base(name="test", project=project)
b.sdf

05:35:47 WARNING:Ungültiger sname-Format: Muss genau zwei Separatoren enthalten
05:35:47 WARNING:'NoneType' object has no attribute 'split'

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T17:35:47.255301+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,test,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__test__0eff89428e034b0a9dfbbde2d59897ae,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [243]:
b = Base(name="test", ns_name="project_sname")
b

In [244]:
b.sname

'Base__test__a5e2dde726b7490f99c733745419cfb7'

In [245]:
b.did

sdata.base:Base sdata-base Base

'did:sd-sdata-base:Base__test__a5e2dde726b7490f99c733745419cfb7'

In [246]:
b.did

sdata.base:Base sdata-base Base

'did:sd-sdata-base:Base__test__a5e2dde726b7490f99c733745419cfb7'

In [247]:
b.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Base,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T15:11:48.806969+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,test,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Base__test__a5e2dde726b7490f99c733745419cfb7,-,str,sname of the data object,,True,
_sdata_suuid,_sdata_suuid,YTVlMmRkZTcyNmI3NDkwZjk5YzczMzc0NTQxOWNmYjdCYX...,-,str,Super Universally Unique Identifier,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,True,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [248]:
b.sname, b.did

sdata.base:Base sdata-base Base

('Base__test__a5e2dde726b7490f99c733745419cfb7',
 'did:sd-sdata-base:Base__test__a5e2dde726b7490f99c733745419cfb7')

In [249]:
sclass_factory

In [250]:
sclass_factory(sdata_spec="Blob")

ModuleNotFoundError: sdata.base.class_factory Error sdata.sclass.spec_to_class Error not enough values to unpack (expected 2, got 1)

In [251]:
sclass_factory("Blob2")

ModuleNotFoundError: sdata.base.class_factory Error sdata.sclass.spec_to_class Error not enough values to unpack (expected 2, got 1)

In [252]:
project = sdata_factory("Project", name="Müller@Scäle.com")
project.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:Project,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T15:11:55.886261+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,Müller@Scäle.com,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,Project__mueller_at_scaele_com__36c52f5326c041...,-,str,sname of the data object,,True,
_sdata_suuid,_sdata_suuid,MzZjNTJmNTMyNmMwNDFhN2E4ODgyMDJlZTY3NGEwNmZQcm...,-,str,Super Universally Unique Identifier,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,True,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [253]:
project

In [254]:
parent = sdata_factory("WTF0815a")
parent.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.base:WTF0815a,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-23T15:11:56.525359+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,WTF0815a__noname__62196db3709549ad9d644fd06de9...,-,str,sname of the data object,,True,
_sdata_suuid,_sdata_suuid,NjIxOTZkYjM3MDk1NDlhZDlkNjQ0ZmQwNmRlOWM0ODNXVE...,-,str,Super Universally Unique Identifier,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,True,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [255]:
b = Base(name="a@b.com" , project=project, parent=parent,
        data={"a":2.3}, ns_name="123")
b.update_data({2:3})
b, b.data

(<Base__a_at_b_com__67fe3f49bd82555c8fd2f6bde8803e4f>, {'a': 2.3, 2: 3})

In [262]:
b.metadata.df.loc["_sdata_name"].value

'a@b.com'

In [260]:
b.data

{'a': 2.3, 2: 3}

In [7]:
b2 = Base.from_json(b.to_json())
b2.sname

'Base@a_b_com@cac3227ea3b25a30b04139b5c982b424'

In [8]:
b.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Base,-,str,sdata class,,True
_sdata_name,_sdata_name,a@b.com,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,WTF0815a@noname@a2dbe559a3b04c94a45fadedae930519,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,Project@mueller_scaele_com@8e27f40ea1c5412682c...,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Base@a_b_com@cac3227ea3b25a30b04139b5c982b424,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,Y2FjMzIyN2VhM2IyNWEzMGIwNDEzOWI1Yzk4MmI0MjRCYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True

In [9]:
m = sdata_factory("Material", name="DP800", project=project, parent=b,
                 default_attributes=[{"name":"a", "value":1.2, "dtype":float, "label":"an a"}])
m

In [10]:
m.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,DP800,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,Base@a_b_com@cac3227ea3b25a30b04139b5c982b424,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,Project@mueller_scaele_com@8e27f40ea1c5412682c...,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@dp800@a056caac4018493881eb784931c6ea25,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,False

In [11]:
m2 = Base.from_json(m.to_json())
m2.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,DP800,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,Base@a_b_com@cac3227ea3b25a30b04139b5c982b424,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,Project@mueller_scaele_com@8e27f40ea1c5412682c...,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@dp800@a056caac4018493881eb784931c6ea25,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,False

In [12]:
type(m), type(m2)

(sdata.base.Material, sdata.base.Material)

In [13]:
issubclass(b.__class__, sdata.base.Base)

True

In [14]:
project.__class__.__bases__

(sdata.base.Base,)

In [15]:
b.sname

'Base@a_b_com@cac3227ea3b25a30b04139b5c982b424'

In [16]:
m.suuid_str

'YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYXRlcmlhbEBkcDgwMA=='

In [17]:
m.suuid_bytes

b'YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYXRlcmlhbEBkcDgwMA=='

In [18]:
m.suuid

(Material@dp800@a056caac4018493881eb784931c6ea25)

In [19]:
m.uuid

UUID('a056caac-4018-4938-81eb-784931c6ea25')

In [20]:
m.suuid.uuid

UUID('a056caac-4018-4938-81eb-784931c6ea25')

In [21]:
m.huuid

'a056caac4018493881eb784931c6ea25'

In [22]:
m.suuid.huuid

'a056caac4018493881eb784931c6ea25'

In [23]:
m.sname

'Material@dp800@a056caac4018493881eb784931c6ea25'

In [24]:
m.suuid.class_name

'Material'

In [25]:
type(m)

sdata.base.Material

In [26]:
m.__class__.__name__

'Material'

In [27]:
m.class_name

'Material'

In [28]:
m.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,DP800,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,Base@a_b_com@cac3227ea3b25a30b04139b5c982b424,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,Project@mueller_scaele_com@8e27f40ea1c5412682c...,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@dp800@a056caac4018493881eb784931c6ea25,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,False

In [29]:
m.to_dict()

{'metadata': {'_sdata_class': {'name': '_sdata_class',
   'value': 'Material',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata class',
   'label': '',
   'required': True},
  '_sdata_name': {'name': '_sdata_name',
   'value': 'DP800',
   'unit': '-',
   'dtype': 'str',
   'description': 'name of the data object',
   'label': '',
   'required': True},
  '_sdata_parent_sname': {'name': '_sdata_parent_sname',
   'value': 'Base@a_b_com@cac3227ea3b25a30b04139b5c982b424',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the parent',
   'label': '',
   'required': False},
  '_sdata_project_sname': {'name': '_sdata_project_sname',
   'value': 'Project@mueller_scaele_com@8e27f40ea1c5412682c66629da8ce113',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the project',
   'label': '',
   'required': False},
  '_sdata_sname': {'name': '_sdata_sname',
   'value': 'Material@dp800@a056caac4018493881eb784931c6ea25',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the data object',
   'label': '',
   'required': True},
  '_sdata_suuid': {'name': '_sdata_suuid',
   'value': 'YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYXRlcmlhbEBkcDgwMA==',
   'unit': '-',
   'dtype': 'str',
   'description': 'Super Universally Unique Identifier',
   'label': '',
   'required': True},
  '_sdata_version': {'name': '_sdata_version',
   'value': '0.26.0',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata package version',
   'label': '',
   'required': True},
  'a': {'name': 'a',
   'value': 1.2,
   'unit': '-',
   'dtype': 'float',
   'description': '',
   'label': 'an a',
   'required': False}},
 'data': {},
 'description': ''}

In [30]:
m2 = Base.from_dict(m.to_dict())
m2.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,DP800,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,Base@a_b_com@cac3227ea3b25a30b04139b5c982b424,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,Project@mueller_scaele_com@8e27f40ea1c5412682c...,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@dp800@a056caac4018493881eb784931c6ea25,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTA1NmNhYWM0MDE4NDkzODgxZWI3ODQ5MzFjNmVhMjVNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,False

In [31]:
Base(default_attributes=[{"name":"a", "value":1.2, "dtype":float, "label":"an a"}]).mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Base,-,str,sdata class,,True
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Base@noname@3f6ced5262f949a988e53f1f5f97f1b0,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,M2Y2Y2VkNTI2MmY5NDlhOTg4ZTUzZjFmNWY5N2YxYjBCYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,False

In [32]:
sdata_factory("Project", name="digipro2green")

In [33]:
p = sdata_factory("Project")
p

In [34]:
p = sdata_factory("Project", name="!!", ns_name="DigiPro2Green")
p

In [35]:
p.name

'!!'

In [36]:
b.md.get(b.SDATA_CLASS)

(Attr'_sdata_class':Base(str))

In [37]:
Base.from_json(project.to_json())

In [38]:
x = Base.from_dict(project.to_dict())
x.class_name

'Project'

In [39]:
m = sdata_factory("Material", Base, default_attributes=[{"name":"a", "value":1.2, "dtype":float, "label":"an a", "required": True}])

p = sdata_factory("Project", m.__class__)
p.__class__, p.__class__.__bases__

(sdata.base.Project, (sdata.base.Material,))

In [40]:
m.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@noname@a6932baa19cc49a1971c7b1e695aa96a,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTY5MzJiYWExOWNjNDlhMTk3MWM3YjFlNjk1YWE5NmFNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,True

In [41]:
p.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Project,-,str,sdata class,,True
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Project@noname@8e3e4b7e61a74e988ed6606333efd51c,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,OGUzZTRiN2U2MWE3NGU5ODhlZDY2MDYzMzNlZmQ1MWNQcm...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True

In [42]:
m.get_project()

In [43]:
m.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@noname@a6932baa19cc49a1971c7b1e695aa96a,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTY5MzJiYWExOWNjNDlhMTk3MWM3YjFlNjk1YWE5NmFNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,True

In [44]:
m.project

In [45]:
m.parent

In [46]:
b.project.sname

'Project@mueller_scaele_com@8e27f40ea1c5412682c66629da8ce113'

In [47]:
b.parent

(WTF0815a@noname@a2dbe559a3b04c94a45fadedae930519)

In [48]:
class Process(Base):
    """Process class

    """

    def __init__(self, **kwargs):
        """

        :param inputs: {}
        :param kwargs:
        """
        self.default_attributes = []
        self.workflow_node_type = 'process'
        self.inputs = kwargs.get("inputs", {})
        self.outputs = kwargs.get("outputs", {})
        self.status = "init"
        super().__init__(**kwargs)
        self.set_default_attributes()
        
po = p = sdata_factory("MyProcessNode", Process)
p.__class__, p.__class__.__bases__
po, po.inputs

(<MyProcessNode@noname@63e2823786e84969b81561be992c5cd9>, {})

In [49]:
po = p = sdata_factory("Project", Process)
p.__class__, p.__class__.__bases__
po, po.inputs

(<Project@noname@7a0e8237c4254174aae946fb5f98b1bd>, {})

In [50]:
m.md.values()

[(Attr'_sdata_class':Material(str)),
 (Attr'_sdata_name':noname(str)),
 (Attr'_sdata_parent_sname':(str)),
 (Attr'_sdata_project_sname':(str)),
 (Attr'_sdata_sname':Material@noname@a6932baa19cc49a1971c7b1e695aa96a(str)),
 (Attr'_sdata_suuid':YTY5MzJiYWExOWNjNDlhMTk3MWM3YjFlNjk1YWE5NmFNYXRlcmlhbEBub25hbWU=(str)),
 (Attr'_sdata_version':0.26.0(str)),
 (Attr'a':1.2(float))]

In [51]:
for attr in m.metadata.values():
    print(attr.required, attr.value)
    if attr.required is True and attr.value is None:
        print(False)
print(True)

True Material
True noname
False
False
True Material@noname@a6932baa19cc49a1971c7b1e695aa96a
True YTY5MzJiYWExOWNjNDlhMTk3MWM3YjFlNjk1YWE5NmFNYXRlcmlhbEBub25hbWU=
True 0.26.0
True 1.2
True

In [52]:
m.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,Material,-,str,sdata class,,True
_sdata_name,_sdata_name,noname,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,Material@noname@a6932baa19cc49a1971c7b1e695aa96a,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,YTY5MzJiYWExOWNjNDlhMTk3MWM3YjFlNjk1YWE5NmFNYX...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,True

In [53]:
b = Base(name="Häl[l]o.csv")
b.name, SUUID.generate_safe_filename(b.name), b.sname

('Häl[l]o.csv',
 'hael_l_o_csv',
 'Base@hael_l_o_csv@35d9d851ed4b4fafb2062a95b6321748')

In [54]:
b.osname

'hael_l_o_csv'

In [55]:
SUUID("MyClass", name="Häl[l]o.csv")

(MyClass@hael_l_o_csv@2ddea91142cf4254a45dd99c07bb01b5)

In [56]:
b = Base(name="test")
assert b.name == "test"

In [57]:
type(b.suuid), b.suuid.__class__

(sdata.suuid.SUUID, sdata.suuid.SUUID)

In [58]:
b = Base(name="test")
assert isinstance(b.suuid, SUUID)

In [59]:
SUUID.generate_safe_filename

In [71]:
import hashlib
s="test text"
sh = hashlib.sha3_256()
sh.update(s.encode('utf-8', errors='strict'))  # Raise bei Encoding-Fehlern
content_hash = sh.hexdigest()
content_hash

'08487142e9585eb2a39f4b8c9f64d4b60dc420af4ee136472d252d0c68d99974'

In [75]:
u = uuid.UUID("1234567890abcdef1234567890abcdef")
sid = SUUID.from_uuid(class_name="Test", uuid_obj=u)
assert sid.class_name == "Test"
assert sid.huuid == "1234567890abcdef1234567890abcdef"
sid.name
#assert sid.name == "noname"

'none'

In [72]:
sid = SUUID.from_str(class_name="Data", s="test text")
print(sid.name)
assert sid.name == expected_hash
# huuid basierend auf "Data" + hash
expected_input = "Data" + expected_hash
expected_uid = uuid.uuid5(uuid.NAMESPACE_OID, expected_input.upper())
assert sid.huuid == expected_uid.hex

_08487142e9585eb2a39f4b8c9f64d4b60dc420af4ee136472d252d0c68d99974

NameError: name 'expected_hash' is not defined

In [60]:
Base@test_name@2f5c692449e95f90a715861f2833d35a
MmY1YzY5MjQ0OWU5NWY5MGE3MTU4NjFmMjgzM2QzNWFCYXNlQHRlc3RfbmFtZQ==

SyntaxError: invalid decimal literal (885436945.py, line 1)

In [76]:
from sdata import Metadata

In [78]:
Metadata.guess_dtype_from_value("True")

(True, 'bool')