In [1]:
#setup notebook
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib notebook
#%autosave 0
import base64
import pandas as pd
import numpy as np
import uuid
import os
import sys
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.WARNING, datefmt='%I:%M:%S')

import sdata
from sdata import SUUID
from sdata.base import Base, sdata_factory
from sdata.sclass.dataframe import DataFrame

In [6]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['apple', 'banana', 'cherry']
})
df.to_parquet('/tmp/df1.pq', index=False)

In [2]:
# Erstelle einen Pandas DataFrame
import pandas as pd

df = pd.DataFrame({
    'weight': [10, 20, 30],
    'height': [1.5, 1.6, 1.7]
})

# Erstelle eine SDataFrame-Instanz mit Metadaten
column_meta = {
    'weight': {'label': 'Gewicht', 'unit': 'kg'},
    'height': {'label': 'Höhe', 'unit': 'm'}
}
sdf = DataFrame(df=df, column_metadata=column_meta, name="MeinDataFrame", description="Beispieldaten")
sdf

In [4]:
df.to_parquet("/tmp/df.pq")

In [5]:
sdf.column_metadata

{'weight': {'label': 'Gewicht', 'unit': 'kg'},
 'height': {'label': 'Höhe', 'unit': 'm'}}

In [6]:
sdf.df

   weight  height
0      10     1.5
1      20     1.6
2      30     1.7

In [7]:
sdf.to_dict()

{'metadata': {'_sdata_bfo_class': {'name': '_sdata_bfo_class',
   'value': 'sdata.sclass:IndependentContinuant',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata bfo class name',
   'label': '',
   'required': True},
  '_sdata_class': {'name': '_sdata_class',
   'value': 'sdata.sclass.dataframe:DataFrame',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata class',
   'label': '',
   'required': True},
  '_sdata_name': {'name': '_sdata_name',
   'value': 'MeinDataFrame',
   'unit': '-',
   'dtype': 'str',
   'description': 'name of the data object',
   'label': '',
   'required': True},
  '_sdata_parent_sname': {'name': '_sdata_parent_sname',
   'value': '',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the parent',
   'label': '',
   'required': False},
  '_sdata_project_sname': {'name': '_sdata_project_sname',
   'value': '',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the project',
   'label': '',
   'required': False},
  '_sdata_sname': {'name': '_sdata_sname',
   'value': 'DataFrame@meindataframe@8f5ad3de0dd64b7483822de013e4ec69',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the data object',
   'label': '',
   'required': True},
  '_sdata_suuid': {'name': '_sdata_suuid',
   'value': 'OGY1YWQzZGUwZGQ2NGI3NDgzODIyZGUwMTNlNGVjNjlEYXRhRnJhbWVAbWVpbmRhdGFmcmFtZQ==',
   'unit': '-',
   'dtype': 'str',
   'description': 'Super Universally Unique Identifier',
   'label': '',
   'required': True},
  '_sdata_version': {'name': '_sdata_version',
   'value': '0.26.0',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata package version',
   'label': '',
   'required': True}},
 'data': {'content': {'type': 'bytes',
   'filetype': 'parquet',
   'value': 'UEFSMRUEFTAVLkwVBhUAEgAAGAQKAAkBPBQAAAAAAAAAHgAAAAAAAAAVABUUFRgsFQYVEBUGFQYcGAgeAAAAAAAAABgICgAAAAAAAAAWACgIHgAAAAAAAAAYCAoAAAAAAAAAAAAACiQCAAAABgECAyQAJuQBHBUEGTUABhAZGAZ3ZWlnaHQVAhYGFtoBFtwBJlImCBwYCB4AAAAAAAAAGAgKAAAAAAAAABYAKAgeAAAAAAAAABgICgAAAAAAAAAAGSwVBBUAFQIAFQAVEBUCAAAAFQQVMBUwTBUGFQASAAAYAAAFAUT4P5qZmZmZmfk/MzMzMzMz+z8VABUUFRgsFQYVEBUGFQYcGAgzMzMzMzP7PxgIAAAAAAAA+D8WACgIMzMzMzMz+z8YCAAAAAAAAPg/AAAACiQCAAAABgECAyQAJoIFHBUKGTUABhAZGAZoZWlnaHQVAhYGFtoBFt4BJvADJqQDHBgIMzMzMzMz+z8YCAAAAAAAAPg/FgAoCDMzMzMzM/s/GAgAAAAAAAD4PwAZLBUEFQAVAgAVABUQFQIAAAAVBBk8NQAYBnNjaGVtYRUEABUEJQIYBndlaWdodAAVCiUCGAZoZWlnaHQAFgYZHBksJuQBHBUEGTUABhAZGAZ3ZWlnaHQVAhYGFtoBFtwBJlImCBwYCB4AAAAAAAAAGAgKAAAAAAAAABYAKAgeAAAAAAAAABgICgAAAAAAAAAAGSwVBBUAFQIAFQAVEBUCAAAAJoIFHBUKGTUABhAZGAZoZWlnaHQVAhYGFtoBFt4BJvADJqQDHBgIMzMzMzMz+z8YCAAAAAAAAPg/FgAoCDMzMzMzM/s/GAgAAAAAAAD4PwAZLBUEFQAVAgAVABUQFQIAAAAWtAMWBiYIFroDFAAAGSwYBnBhbmRhcxihBHsiaW5kZXhfY29sdW1ucyI6IFt7ImtpbmQiOiAicmFuZ2UiLCAibmFtZSI6IG51bGwsICJzdGFydCI6IDAsICJzdG9wIjogMywgInN0ZXAiOiAxfV0sICJjb2x1bW5faW5kZXhlcyI6IFt7Im5hbWUiOiBudWxsLCAiZmllbGRfbmFtZSI6IG51bGwsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogeyJlbmNvZGluZyI6ICJVVEYtOCJ9fV0sICJjb2x1bW5zIjogW3sibmFtZSI6ICJ3ZWlnaHQiLCAiZmllbGRfbmFtZSI6ICJ3ZWlnaHQiLCAicGFuZGFzX3R5cGUiOiAiaW50NjQiLCAibnVtcHlfdHlwZSI6ICJpbnQ2NCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAiaGVpZ2h0IiwgImZpZWxkX25hbWUiOiAiaGVpZ2h0IiwgInBhbmRhc190eXBlIjogImZsb2F0NjQiLCAibnVtcHlfdHlwZSI6ICJmbG9hdDY0IiwgIm1ldGFkYXRhIjogbnVsbH1dLCAiY3JlYXRvciI6IHsibGlicmFyeSI6ICJweWFycm93IiwgInZlcnNpb24iOiAiMTcuMC4wIn0sICJwYW5kYXNfdmVyc2lvbiI6ICIyLjIuMyJ9ABgMQVJST1c6c2NoZW1hGKAILy8vLy94QURBQUFRQUFBQUFBQUtBQTRBQmdBRkFBZ0FDZ0FBQUFBQkJBQVFBQUFBQUFBS0FBd0FBQUFFQUFnQUNnQUFBRmdDQUFBRUFBQUFBUUFBQUF3QUFBQUlBQXdBQkFBSUFBZ0FBQUF3QWdBQUJBQUFBQ0VDQUFCN0ltbHVaR1Y0WDJOdmJIVnRibk1pT2lCYmV5SnJhVzVrSWpvZ0luSmhibWRsSWl3Z0ltNWhiV1VpT2lCdWRXeHNMQ0FpYzNSaGNuUWlPaUF3TENBaWMzUnZjQ0k2SURNc0lDSnpkR1Z3SWpvZ01YMWRMQ0FpWTI5c2RXMXVYMmx1WkdWNFpYTWlPaUJiZXlKdVlXMWxJam9nYm5Wc2JDd2dJbVpwWld4a1gyNWhiV1VpT2lCdWRXeHNMQ0FpY0dGdVpHRnpYM1I1Y0dVaU9pQWlkVzVwWTI5a1pTSXNJQ0p1ZFcxd2VWOTBlWEJsSWpvZ0ltOWlhbVZqZENJc0lDSnRaWFJoWkdGMFlTSTZJSHNpWlc1amIyUnBibWNpT2lBaVZWUkdMVGdpZlgxZExDQWlZMjlzZFcxdWN5STZJRnQ3SW01aGJXVWlPaUFpZDJWcFoyaDBJaXdnSW1acFpXeGtYMjVoYldVaU9pQWlkMlZwWjJoMElpd2dJbkJoYm1SaGMxOTBlWEJsSWpvZ0ltbHVkRFkwSWl3Z0ltNTFiWEI1WDNSNWNHVWlPaUFpYVc1ME5qUWlMQ0FpYldWMFlXUmhkR0VpT2lCdWRXeHNmU3dnZXlKdVlXMWxJam9nSW1obGFXZG9kQ0lzSUNKbWFXVnNaRjl1WVcxbElqb2dJbWhsYVdkb2RDSXNJQ0p3WVc1a1lYTmZkSGx3WlNJNklDSm1iRzloZERZMElpd2dJbTUxYlhCNVgzUjVjR1VpT2lBaVpteHZZWFEyTkNJc0lDSnRaWFJoWkdGMFlTSTZJRzUxYkd4OVhTd2dJbU55WldGMGIzSWlPaUI3SW14cFluSmhjbmtpT2lBaWNIbGhjbkp2ZHlJc0lDSjJaWEp6YVc5dUlqb2dJakUzTGpBdU1DSjlMQ0FpY0dGdVpHRnpYM1psY25OcGIyNGlPaUFpTWk0eUxqTWlmUUFBQUFZQUFBQndZVzVrWVhNQUFBSUFBQUJNQUFBQUJBQUFBTXovLy84QUFBRURFQUFBQUNBQUFBQUVBQUFBQUFBQUFBWUFBQUJvWldsbmFIUUFBQUFBQmdBSUFBWUFCZ0FBQUFBQUFnQVFBQlFBQ0FBR0FBY0FEQUFBQUJBQUVBQUFBQUFBQVFJUUFBQUFJQUFBQUFRQUFBQUFBQUFBQmdBQUFIZGxhV2RvZEFBQUNBQU1BQWdBQndBSUFBQUFBQUFBQVVBQUFBQUFBQUFBABggcGFycXVldC1jcHAtYXJyb3cgdmVyc2lvbiAxNy4wLjAZLBwAABwAAACMBwAAUEFSMQ=='},
  'column_metadata': {'weight': {'label': 'Gewicht', 'unit': 'kg'},
   'height': {'label': 'Höhe', 'unit': 'm'}},
  'df_cached':    weight  height
  0      10     1.5
  1      20     1.6
  2      30     1.7},
 'description': 'Beispieldaten'}

In [8]:
sdf.df

   weight  height
0      10     1.5
1      20     1.6
2      30     1.7

In [9]:
d2 = DataFrame.from_dict(sdf.to_dict())
d2.df

AttributeError: 'DataFrame' object has no attribute 'df'

In [10]:
serialized = sdf.to_dict()
restored_sdf = DataFrame.from_dict(serialized)
print(restored_sdf.df)

AttributeError: 'DataFrame' object has no attribute 'df'

In [ ]:
type(restored_sdf)

In [ ]:
DataFrame().df

In [13]:
sdata_factory("A", DataFrame).df

ValueError: No value set in content.