In [1]:
#setup notebook
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib notebook
#%autosave 0
import base64
import pandas as pd
import numpy as np
import uuid
import os
import sys
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.WARNING, datefmt='%I:%M:%S')

import sdata
from sdata import SUUID
from sdata.sclass.process import SpecificInput, SpecificOutput, ProcessData, ProcessNode, SpecificProcessNode

In [2]:
import sdata.base
s= SUUID(class_name="a", name="b")
j = sdata.base.to_json(s) 
j

AttributeError: module 'sdata.base' has no attribute 'to_json'

In [ ]:
s.to_dict()

In [ ]:
sdata.base.from_json(j)

In [ ]:
sdata.base.obj_to_spec(s)

In [3]:
input_a = SpecificInput(name="input", attributes=[{"name":"a", "value": 1.2},
                                                  {"name":"b", "value": 3}])
input_a.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_bfo_class,_sdata_bfo_class,sdata.sclass:GenericallyDependentContinuant,-,str,sdata bfo class name,,True
_sdata_class,_sdata_class,sdata.sclass.process:SpecificInput,-,str,sdata class,,True
_sdata_name,_sdata_name,input,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,SpecificInput@input@e4148fd84e9f4ef5bde1633edc...,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,ZTQxNDhmZDg0ZTlmNGVmNWJkZTE2MzNlZGM0Y2ZmMzdTcG...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,my a value,$a$,True
b,b,3,MPa,int,my b value,$b$,True

In [4]:
type(input_a)

sdata.sclass.process.SpecificInput

In [16]:
s= SUUID(class_name="a", name="b")
type(s)

sdata.suuid.SUUID

In [11]:
input_a.default_attributes

[{'name': 'a',
  'value': None,
  'dtype': float,
  'label': 'an a',
  'required': True},
 {'name': 'b', 'value': None, 'dtype': int, 'label': 'an b', 'required': True}]

In [12]:
input_a.mdf

,name,value,unit,dtype,description,label,required
key,,,,,,,
_sdata_class,_sdata_class,SpecificInput,-,str,sdata class,,True
_sdata_name,_sdata_name,input,-,str,name of the data object,,True
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False
_sdata_sname,_sdata_sname,SpecificInput@input@2ab239d60f024404b673ce587b...,-,str,sname of the data object,,True
_sdata_suuid,_sdata_suuid,MmFiMjM5ZDYwZjAyNDQwNGI2NzNjZTU4N2IyN2ViZmRTcG...,-,str,Super Universally Unique Identifier,,True
_sdata_version,_sdata_version,0.26.0,-,str,sdata package version,,True
a,a,1.2,-,float,,an a,True
b,b,3,-,int,,an b,True

In [13]:
input_a.is_complete()

True

In [14]:
# Gültiger Knoten
node = SpecificProcessNode(
    name="MyNode",
    inputs={"input1": input_a}
)
try:
    node.validate_inputs()  # Erfolgreich
    outputs = node.run()  # Erzeugt Outputs
    print("Valid node ran successfully.")
except ValueError as e:
    print(f"Valid node error: {e}")
node

Valid node ran successfully.

In [15]:
node.outputs['output1'].udf

    name  value unit  dtype description label  required
key
c      c    4.2    -  float                       False

In [8]:

input_a = SpecificInput(name="input", attributes=[{"name": "a", "value": 1.2},
                                                  {"name": "b", "value": 3}])
# Gültiger Knoten
node = SpecificProcessNode(
    name="MyNode",
    inputs={"input1": SpecificInput(name="Input1", metadata={"data": "value"})}
)
try:
    node.validate_inputs()  # Erfolgreich
    outputs = node.run()  # Erzeugt Outputs
    print("Valid node ran successfully.")
except ValueError as e:
    print(f"Valid node error: {e}")
node

Valid node ran successfully.