In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%autosave 0
    
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

import os
import sys
import numpy as np
import pandas as pd
import sdata
import uuid
modulepath = os.getcwd()
modulepath

Autosave disabled

'/home/ingolf.lepenies/projects/sdata/ipynb'

02:26:59 DEBUG:Loaded backend module://ipykernel.pylab.backend_inline version unknown.

In [2]:
workpath = os.path.abspath(os.path.join("..", "data", "numisheet_2020"))
workpath
os.listdir(workpath)

['analyze-NS-rawdata.csv',
 'numisheet_2020_tensioncompression.xlsx',
 '.~lock.numisheet_2020_tensioncompression.xlsx#',
 'README.md',
 'analyze-NS-rawdata-attributes.csv',
 'numisheet_2020_tensioncompression.json']

In [3]:
df_meta = pd.read_csv(os.path.join(workpath, "analyze-NS-rawdata-attributes.csv"))
df_meta.drop_duplicates(inplace=True)
df_meta

,Variable,Units,Type,Description,AxisLabel
0,Time,s,Real,Time,Time /s
1,Displacement,mm,Real,Actuator displacement,Actuator displacement /mm
3,Force,N,Real,Load washer force,NaN
4,Estress,MPa,Real,Engineering stress,NaN
5,Estrain,mm/mm,Real,Engineering strain,NaN
6,Tstress,MPa,Real,True stress,NaN
7,Tstrain,mm/mm,Real,True strain,NaN
8,EstrainRate,mm/mm/s,Real,Engineering strain rate computed from smooth s...,NaN
9,Experiment,NaN,Char,NCAL Experiment descriptor,NaN
10,Specimen,NaN,Char,NCAL Specimen descriptor,NaN
11,Material,NaN,Char,Material Descriptor: �1008|Al2024|TRIP�,NaN
12,Material,NaN,Char,describes heat treatment. Retained for compati...,NaN
13,Geometry,NaN,Char,description of major specimen geometry compone...,NaN
15,Path,NaN,Char,"strain path for test C=compression, T =tension",NaN
16,NumisheetID,NaN,Char,"Numisheet 2020 Material designation, per Tom S...",NaN
17,IntendedRate,mm/s,Real,Intended actuator velocity,NaN
18,ASPID,NaN,Char,ASP Materials Bank ID,NaN
19,dedt,mm/mm/s,Real,achieved specimen engineering strain rate,NaN
20,dedtnomlabel,NaN,Character,convenient axis label,NaN
21,StrainA,mm/mm,Real,Engineering strain based on a gauge length equ...,NaN
22,StrainfG,mm/mm,NaN,Engineering strain based on a gauge length equ...,NaN
23,eyyA,mm/mm,Real,Average engineering strain in the entire reduc...,NaN
24,eyyfgA,mm/mm,Real,Average engineering strain in the central 4/7 ...,NaN

In [4]:
df_meta.rename(columns={"Variable":"name",
                       "Units":"unit",
                       "Description":"description"}, inplace=True)
df_meta

,name,unit,Type,description,AxisLabel
0,Time,s,Real,Time,Time /s
1,Displacement,mm,Real,Actuator displacement,Actuator displacement /mm
3,Force,N,Real,Load washer force,NaN
4,Estress,MPa,Real,Engineering stress,NaN
5,Estrain,mm/mm,Real,Engineering strain,NaN
6,Tstress,MPa,Real,True stress,NaN
7,Tstrain,mm/mm,Real,True strain,NaN
8,EstrainRate,mm/mm/s,Real,Engineering strain rate computed from smooth s...,NaN
9,Experiment,NaN,Char,NCAL Experiment descriptor,NaN
10,Specimen,NaN,Char,NCAL Specimen descriptor,NaN
11,Material,NaN,Char,Material Descriptor: �1008|Al2024|TRIP�,NaN
12,Material,NaN,Char,describes heat treatment. Retained for compati...,NaN
13,Geometry,NaN,Char,description of major specimen geometry compone...,NaN
15,Path,NaN,Char,"strain path for test C=compression, T =tension",NaN
16,NumisheetID,NaN,Char,"Numisheet 2020 Material designation, per Tom S...",NaN
17,IntendedRate,mm/s,Real,Intended actuator velocity,NaN
18,ASPID,NaN,Char,ASP Materials Bank ID,NaN
19,dedt,mm/mm/s,Real,achieved specimen engineering strain rate,NaN
20,dedtnomlabel,NaN,Character,convenient axis label,NaN
21,StrainA,mm/mm,Real,Engineering strain based on a gauge length equ...,NaN
22,StrainfG,mm/mm,NaN,Engineering strain based on a gauge length equ...,NaN
23,eyyA,mm/mm,Real,Average engineering strain in the entire reduc...,NaN
24,eyyfgA,mm/mm,Real,Average engineering strain in the central 4/7 ...,NaN

In [5]:
df_meta["type"] = df_meta.Type.astype(str)
df_meta

,name,unit,Type,description,AxisLabel,type
0,Time,s,Real,Time,Time /s,Real
1,Displacement,mm,Real,Actuator displacement,Actuator displacement /mm,Real
3,Force,N,Real,Load washer force,NaN,Real
4,Estress,MPa,Real,Engineering stress,NaN,Real
5,Estrain,mm/mm,Real,Engineering strain,NaN,Real
6,Tstress,MPa,Real,True stress,NaN,Real
7,Tstrain,mm/mm,Real,True strain,NaN,Real
8,EstrainRate,mm/mm/s,Real,Engineering strain rate computed from smooth s...,NaN,Real
9,Experiment,NaN,Char,NCAL Experiment descriptor,NaN,Char
10,Specimen,NaN,Char,NCAL Specimen descriptor,NaN,Char
11,Material,NaN,Char,Material Descriptor: �1008|Al2024|TRIP�,NaN,Char
12,Material,NaN,Char,describes heat treatment. Retained for compati...,NaN,Char
13,Geometry,NaN,Char,description of major specimen geometry compone...,NaN,Char
15,Path,NaN,Char,"strain path for test C=compression, T =tension",NaN,Char
16,NumisheetID,NaN,Char,"Numisheet 2020 Material designation, per Tom S...",NaN,Char
17,IntendedRate,mm/s,Real,Intended actuator velocity,NaN,Real
18,ASPID,NaN,Char,ASP Materials Bank ID,NaN,Char
19,dedt,mm/mm/s,Real,achieved specimen engineering strain rate,NaN,Real
20,dedtnomlabel,NaN,Character,convenient axis label,NaN,Character
21,StrainA,mm/mm,Real,Engineering strain based on a gauge length equ...,NaN,Real
22,StrainfG,mm/mm,NaN,Engineering strain based on a gauge length equ...,NaN,nan
23,eyyA,mm/mm,Real,Average engineering strain in the entire reduc...,NaN,Real
24,eyyfgA,mm/mm,Real,Average engineering strain in the central 4/7 ...,NaN,Real

In [6]:
df_meta["dtype"] = df_meta.Type.astype(str)
df_meta.dtype = df_meta.dtype.map({"Real":"float", "Char":"str", "Character":"float", "nan":"float"})
df_meta

,name,unit,Type,description,AxisLabel,type,dtype
0,Time,s,Real,Time,Time /s,Real,float
1,Displacement,mm,Real,Actuator displacement,Actuator displacement /mm,Real,float
3,Force,N,Real,Load washer force,NaN,Real,float
4,Estress,MPa,Real,Engineering stress,NaN,Real,float
5,Estrain,mm/mm,Real,Engineering strain,NaN,Real,float
6,Tstress,MPa,Real,True stress,NaN,Real,float
7,Tstrain,mm/mm,Real,True strain,NaN,Real,float
8,EstrainRate,mm/mm/s,Real,Engineering strain rate computed from smooth s...,NaN,Real,float
9,Experiment,NaN,Char,NCAL Experiment descriptor,NaN,Char,str
10,Specimen,NaN,Char,NCAL Specimen descriptor,NaN,Char,str
11,Material,NaN,Char,Material Descriptor: �1008|Al2024|TRIP�,NaN,Char,str
12,Material,NaN,Char,describes heat treatment. Retained for compati...,NaN,Char,str
13,Geometry,NaN,Char,description of major specimen geometry compone...,NaN,Char,str
15,Path,NaN,Char,"strain path for test C=compression, T =tension",NaN,Char,str
16,NumisheetID,NaN,Char,"Numisheet 2020 Material designation, per Tom S...",NaN,Char,str
17,IntendedRate,mm/s,Real,Intended actuator velocity,NaN,Real,float
18,ASPID,NaN,Char,ASP Materials Bank ID,NaN,Char,str
19,dedt,mm/mm/s,Real,achieved specimen engineering strain rate,NaN,Real,float
20,dedtnomlabel,NaN,Character,convenient axis label,NaN,Character,float
21,StrainA,mm/mm,Real,Engineering strain based on a gauge length equ...,NaN,Real,float
22,StrainfG,mm/mm,NaN,Engineering strain based on a gauge length equ...,NaN,nan,float
23,eyyA,mm/mm,Real,Average engineering strain in the entire reduc...,NaN,Real,float
24,eyyfgA,mm/mm,Real,Average engineering strain in the central 4/7 ...,NaN,Real,float

In [7]:
df_meta["value"] = None
df_meta.drop(columns=["Type", "AxisLabel"], inplace=True)
df_meta

,name,unit,description,type,dtype,value
0,Time,s,Time,Real,float,None
1,Displacement,mm,Actuator displacement,Real,float,None
3,Force,N,Load washer force,Real,float,None
4,Estress,MPa,Engineering stress,Real,float,None
5,Estrain,mm/mm,Engineering strain,Real,float,None
6,Tstress,MPa,True stress,Real,float,None
7,Tstrain,mm/mm,True strain,Real,float,None
8,EstrainRate,mm/mm/s,Engineering strain rate computed from smooth s...,Real,float,None
9,Experiment,NaN,NCAL Experiment descriptor,Char,str,None
10,Specimen,NaN,NCAL Specimen descriptor,Char,str,None
11,Material,NaN,Material Descriptor: �1008|Al2024|TRIP�,Char,str,None
12,Material,NaN,describes heat treatment. Retained for compati...,Char,str,None
13,Geometry,NaN,description of major specimen geometry compone...,Char,str,None
15,Path,NaN,"strain path for test C=compression, T =tension",Char,str,None
16,NumisheetID,NaN,"Numisheet 2020 Material designation, per Tom S...",Char,str,None
17,IntendedRate,mm/s,Intended actuator velocity,Real,float,None
18,ASPID,NaN,ASP Materials Bank ID,Char,str,None
19,dedt,mm/mm/s,achieved specimen engineering strain rate,Real,float,None
20,dedtnomlabel,NaN,convenient axis label,Character,float,None
21,StrainA,mm/mm,Engineering strain based on a gauge length equ...,Real,float,None
22,StrainfG,mm/mm,Engineering strain based on a gauge length equ...,nan,float,None
23,eyyA,mm/mm,Average engineering strain in the entire reduc...,Real,float,None
24,eyyfgA,mm/mm,Average engineering strain in the central 4/7 ...,Real,float,None

In [8]:
df_meta.set_index(df_meta.name, inplace=True)

In [9]:
df_meta.columns
df_meta = df_meta[['name', 'value', 'dtype', 'unit', 'description']]
df_meta

,name,value,dtype,unit,description
name,,,,,
Time,Time,None,float,s,Time
Displacement,Displacement,None,float,mm,Actuator displacement
Force,Force,None,float,N,Load washer force
Estress,Estress,None,float,MPa,Engineering stress
Estrain,Estrain,None,float,mm/mm,Engineering strain
Tstress,Tstress,None,float,MPa,True stress
Tstrain,Tstrain,None,float,mm/mm,True strain
EstrainRate,EstrainRate,None,float,mm/mm/s,Engineering strain rate computed from smooth s...
Experiment,Experiment,None,str,NaN,NCAL Experiment descriptor
Specimen,Specimen,None,str,NaN,NCAL Specimen descriptor
Material,Material,None,str,NaN,Material Descriptor: �1008|Al2024|TRIP�
Material,Material,None,str,NaN,describes heat treatment. Retained for compati...
Geometry,Geometry,None,str,NaN,description of major specimen geometry compone...
Path,Path,None,str,NaN,"strain path for test C=compression, T =tension"
NumisheetID,NumisheetID,None,str,NaN,"Numisheet 2020 Material designation, per Tom S..."
IntendedRate,IntendedRate,None,float,mm/s,Intended actuator velocity
ASPID,ASPID,None,str,NaN,ASP Materials Bank ID
dedt,dedt,None,float,mm/mm/s,achieved specimen engineering strain rate
dedtnomlabel,dedtnomlabel,None,float,NaN,convenient axis label
StrainA,StrainA,None,float,mm/mm,Engineering strain based on a gauge length equ...
StrainfG,StrainfG,None,float,mm/mm,Engineering strain based on a gauge length equ...
eyyA,eyyA,None,float,mm/mm,Average engineering strain in the entire reduc...
eyyfgA,eyyfgA,None,float,mm/mm,Average engineering strain in the central 4/7 ...

In [10]:
df_meta.values.tolist()

[['Time', None, 'float', 's', 'Time'],
 ['Displacement', None, 'float', 'mm', 'Actuator displacement'],
 ['Force', None, 'float', 'N', 'Load washer force'],
 ['Estress', None, 'float', 'MPa', 'Engineering stress'],
 ['Estrain', None, 'float', 'mm/mm', 'Engineering strain'],
 ['Tstress', None, 'float', 'MPa', 'True stress'],
 ['Tstrain', None, 'float', 'mm/mm', 'True strain'],
 ['EstrainRate',
  None,
  'float',
  'mm/mm/s',
  'Engineering strain rate computed from smooth spline'],
 ['Experiment', None, 'str', nan, 'NCAL Experiment descriptor'],
 ['Specimen', None, 'str', nan, 'NCAL Specimen descriptor'],
 ['Material', None, 'str', nan, 'Material Descriptor: �1008|Al2024|TRIP�'],
 ['Material',
  None,
  'str',
  nan,
  'describes heat treatment. Retained for compatibility with other scripts'],
 ['Geometry',
  None,
  'str',
  nan,
  'description of major specimen geometry components by concatenating reduced parallel length, fillet radius and width'],
 ['Path', None, 'str', nan, 'strain path for test C=compression, T =tension'],
 ['NumisheetID',
  None,
  'str',
  nan,
  'Numisheet 2020 Material designation, per Tom Stoughton 2019-11-19 email'],
 ['IntendedRate', None, 'float', 'mm/s', 'Intended actuator velocity'],
 ['ASPID', None, 'str', nan, 'ASP Materials Bank ID'],
 ['dedt',
  None,
  'float',
  'mm/mm/s',
  'achieved specimen engineering strain rate'],
 ['dedtnomlabel', None, 'float', nan, 'convenient axis label'],
 ['StrainA',
  None,
  'float',
  'mm/mm',
  'Engineering strain based on a gauge length equal to the reduced parallel length'],
 ['StrainfG',
  None,
  'float',
  'mm/mm',
  'Engineering strain based on a gauge length equal to 4/7 of the reduced parallel length'],
 ['eyyA',
  None,
  'float',
  'mm/mm',
  'Average engineering strain in the entire reduced parallel length'],
 ['eyyfgA',
  None,
  'float',
  'mm/mm',
  'Average engineering strain in the central 4/7 of the reduced parallel length']]

In [11]:
metadata = sdata.Metadata.from_list(df_meta.values.tolist())
metadata.df

,name,value,dtype,unit,description
key,,,,,
Time,Time,None,float,s,Time
Displacement,Displacement,None,float,mm,Actuator displacement
Force,Force,None,float,N,Load washer force
Estress,Estress,None,float,MPa,Engineering stress
Estrain,Estrain,None,float,mm/mm,Engineering strain
Tstress,Tstress,None,float,MPa,True stress
Tstrain,Tstrain,None,float,mm/mm,True strain
EstrainRate,EstrainRate,None,float,mm/mm/s,Engineering strain rate computed from smooth s...
Experiment,Experiment,None,str,NaN,NCAL Experiment descriptor
Specimen,Specimen,None,str,NaN,NCAL Specimen descriptor
Material,Material,None,str,NaN,describes heat treatment. Retained for compati...
Geometry,Geometry,None,str,NaN,description of major specimen geometry compone...
Path,Path,None,str,NaN,"strain path for test C=compression, T =tension"
NumisheetID,NumisheetID,None,str,NaN,"Numisheet 2020 Material designation, per Tom S..."
IntendedRate,IntendedRate,None,float,mm/s,Intended actuator velocity
ASPID,ASPID,None,str,NaN,ASP Materials Bank ID
dedt,dedt,None,float,mm/mm/s,achieved specimen engineering strain rate
dedtnomlabel,dedtnomlabel,None,float,NaN,convenient axis label
StrainA,StrainA,None,float,mm/mm,Engineering strain based on a gauge length equ...
StrainfG,StrainfG,None,float,mm/mm,Engineering strain based on a gauge length equ...
eyyA,eyyA,None,float,mm/mm,Average engineering strain in the entire reduc...
eyyfgA,eyyfgA,None,float,mm/mm,Average engineering strain in the central 4/7 ...

In [12]:
df_exp = pd.read_csv(os.path.join(workpath, "analyze-NS-rawdata.csv"))
df_exp.drop_duplicates(inplace=True)
df_exp

,Time,Displacement,Force,Estress,Estrain,Tstress,Tstrain,Specimen,Material,Geometry,...,dedt,IntendedRate,StrainA,StrainfG,eyyA,eyyfgA,Path,ASPID,NumisheetID,dedtnomlabel
0,0.0000,-39.8488,2.0,0.106611,0.000000e+00,0.106611,0.000000e+00,S190918-ERR-071,DP1180,A36R19W18,...,NaN,0.00025,0.000000e+00,0.000000e+00,-0.000008,-1.490744e-05,TCT,LOT#19: 1.00x CR825Y1180T-DP-UNCOATED-U,NaN,0.00025 mm/mm/s
1,0.1998,-39.8488,0.0,0.000000,-2.387196e-06,0.000000,-2.387199e-06,S190918-ERR-071,DP1180,A36R19W18,...,NaN,0.00025,-2.387196e-06,-1.660862e-05,-0.000018,-3.191302e-05,TCT,LOT#19: 1.00x CR825Y1180T-DP-UNCOATED-U,NaN,0.00025 mm/mm/s
2,0.3998,-39.8408,0.5,0.026653,-9.703206e-06,0.026652,-9.703253e-06,S190918-ERR-071,DP1180,A36R19W18,...,NaN,0.00025,-9.703206e-06,-1.199776e-05,-0.000023,-2.356464e-05,TCT,LOT#19: 1.00x CR825Y1180T-DP-UNCOATED-U,NaN,0.00025 mm/mm/s
3,0.5997,-39.8464,0.0,0.000000,7.457243e-06,0.000000,7.457216e-06,S190918-ERR-071,DP1180,A36R19W18,...,NaN,0.00025,7.457243e-06,1.634256e-05,0.000002,8.166672e-07,TCT,LOT#19: 1.00x CR825Y1180T-DP-UNCOATED-U,NaN,0.00025 mm/mm/s
4,0.7998,-39.8544,1.5,0.079958,-6.686905e-07,0.079958,-6.686907e-07,S190918-ERR-071,DP1180,A36R19W18,...,NaN,0.00025,-6.686905e-07,6.182839e-07,-0.000009,-1.094360e-05,TCT,LOT#19: 1.00x CR825Y1180T-DP-UNCOATED-U,NaN,0.00025 mm/mm/s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27775,926.9503,-39.6728,20554.5,1080.533708,1.523150e-01,1245.115188,1.417730e-01,S200123-ERR-076,DP1180,A36R19W18,...,NaN,0.00025,1.523150e-01,1.809150e-01,0.153237,1.838798e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27776,927.9503,-39.6752,20452.5,1075.171649,1.527800e-01,1239.436373,1.421764e-01,S200123-ERR-076,DP1180,A36R19W18,...,NaN,0.00025,1.527800e-01,1.817564e-01,0.153766,1.848752e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27777,928.9504,-39.6544,20372.5,1070.966113,1.532584e-01,1235.100708,1.425914e-01,S200123-ERR-076,DP1180,A36R19W18,...,NaN,0.00025,1.532584e-01,1.825970e-01,0.154237,1.858361e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27778,929.9504,-39.6488,20254.0,1064.736662,1.537417e-01,1228.431038,1.430103e-01,S200123-ERR-076,DP1180,A36R19W18,...,NaN,0.00025,1.537417e-01,1.834580e-01,0.154888,1.871302e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27779,930.9505,-39.6360,20132.0,1058.323219,1.542152e-01,1221.532737,1.434206e-01,S200123-ERR-076,DP1180,A36R19W18,...,NaN,0.00025,1.542152e-01,1.843130e-01,0.155226,1.878355e-01,TCT,NaN,NaN,0.00025 mm/mm/s

In [13]:
name = "Numisheet_2020_TensionCompression"
description = "https://data.nist.gov/od/id/mds2-2202 file analyze-NS-rawdata.csv 2020-12-07"
data = sdata.Data(name=name, metadata=metadata, uuid=sdata.uuid_from_str(name), table=df_exp, description=description)
data

(Data 'Numisheet_2020_TensionCompression':e84f95393cb0308899d11a9fced291bf)

In [14]:
data.describe()

                   0
metadata          24
table_rows     27780
table_columns     21
description       76

In [15]:
data.to_xlsx(os.path.join(workpath, data.osname+".xlsx"))

In [16]:
data.to_json(filepath=os.path.join(workpath, data.osname+".json"))

In [17]:
d = data.from_json(filepath=os.path.join(workpath, data.osname+".json"))
d.describe()

02:27:16 INFO:NumExpr defaulting to 8 threads.

                   0
metadata          24
table_rows     27780
table_columns     21
description       76

In [31]:
data.to_csv(os.path.join(workpath, data.osname+".csv"))

In [ ]:
import json
json.dump()

In [36]:
s = data.df.to_csv(sep=";")

In [41]:
s = data.to_csv()
s[:200]

'#;Time;;s;float;Time\n#;Displacement;;mm;float;Actuator displacement\n#;Force;;N;float;Load washer force\n#;Estress;;MPa;float;Engineering stress\n#;Estrain;;mm/mm;float;Engineering strain\n#;Tstress;;MPa;'

In [44]:
d = data.from_csv(s)
d.describe()

               0
metadata       3
table_rows     0
table_columns  0
description    0

In [46]:
import io
sio = io.StringIO(s)
pd.read_csv(sio, sep=";", comment="#")

,index,Time,Displacement,Force,Estress,Estrain,Tstress,Tstrain,Specimen,Material,...,dedt,IntendedRate,StrainA,StrainfG,eyyA,eyyfgA,Path,ASPID,NumisheetID,dedtnomlabel
0,0,0.0000,-39.8488,2.0,0.106611,0.000000e+00,0.106611,0.000000e+00,S190918-ERR-071,DP1180,...,NaN,0.00025,0.000000e+00,0.000000e+00,-0.000008,-1.490744e-05,TCT,LOT,NaN,NaN
1,1,0.1998,-39.8488,0.0,0.000000,-2.387196e-06,0.000000,-2.387199e-06,S190918-ERR-071,DP1180,...,NaN,0.00025,-2.387196e-06,-1.660862e-05,-0.000018,-3.191302e-05,TCT,LOT,NaN,NaN
2,2,0.3998,-39.8408,0.5,0.026653,-9.703206e-06,0.026652,-9.703253e-06,S190918-ERR-071,DP1180,...,NaN,0.00025,-9.703206e-06,-1.199776e-05,-0.000023,-2.356464e-05,TCT,LOT,NaN,NaN
3,3,0.5997,-39.8464,0.0,0.000000,7.457243e-06,0.000000,7.457216e-06,S190918-ERR-071,DP1180,...,NaN,0.00025,7.457243e-06,1.634256e-05,0.000002,8.166672e-07,TCT,LOT,NaN,NaN
4,4,0.7998,-39.8544,1.5,0.079958,-6.686905e-07,0.079958,-6.686907e-07,S190918-ERR-071,DP1180,...,NaN,0.00025,-6.686905e-07,6.182839e-07,-0.000009,-1.094360e-05,TCT,LOT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27775,27775,926.9503,-39.6728,20554.5,1080.533708,1.523150e-01,1245.115188,1.417730e-01,S200123-ERR-076,DP1180,...,NaN,0.00025,1.523150e-01,1.809150e-01,0.153237,1.838798e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27776,27776,927.9503,-39.6752,20452.5,1075.171649,1.527800e-01,1239.436373,1.421764e-01,S200123-ERR-076,DP1180,...,NaN,0.00025,1.527800e-01,1.817564e-01,0.153766,1.848752e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27777,27777,928.9504,-39.6544,20372.5,1070.966113,1.532584e-01,1235.100708,1.425914e-01,S200123-ERR-076,DP1180,...,NaN,0.00025,1.532584e-01,1.825970e-01,0.154237,1.858361e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27778,27778,929.9504,-39.6488,20254.0,1064.736662,1.537417e-01,1228.431038,1.430103e-01,S200123-ERR-076,DP1180,...,NaN,0.00025,1.537417e-01,1.834580e-01,0.154888,1.871302e-01,TCT,NaN,NaN,0.00025 mm/mm/s
27779,27779,930.9505,-39.6360,20132.0,1058.323219,1.542152e-01,1221.532737,1.434206e-01,S200123-ERR-076,DP1180,...,NaN,0.00025,1.542152e-01,1.843130e-01,0.155226,1.878355e-01,TCT,NaN,NaN,0.00025 mm/mm/s

In [22]:
d=sdata.Data()
d.metadata.df

,name,value,dtype,unit,description
key,,,,,
sdata_version,sdata_version,0.8.0,str,-,
name,name,N.N.,str,-,
uuid,uuid,dcc34869565c4644b42215368748737a,str,-,