# sdata.Attribute

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib notebook
%autosave 0
    
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

import os
import sys
import numpy as np
import pandas as pd
import sdata

03:02:45 INFO:Note: NumExpr detected 22 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
03:02:45 INFO:NumExpr defaulting to 16 threads.

Autosave disabled

In [2]:
m = sdata.Metadata(name="My first metadata")
m

(Metadata'My first metadata':0)

In [3]:
#help(m)

# sdata.Attribute

create a simple key-value-Attribute

In [4]:
value = 1
print(sdata.Attribute.guess_dtype(value))
a = sdata.Attribute("otto1", value, dtype=int, ontology="BFO0815")
a.to_dict()

<class 'int'>

{'name': 'otto1',
 'value': 1,
 'unit': '-',
 'dtype': 'int',
 'description': '',
 'label': '',
 'required': False,
 'ontology': 'BFO0815'}

In [5]:
value = [1, "a"]
print(sdata.Attribute.guess_dtype(value))
b = sdata.Attribute("ls", value, dtype=list, ontology="BFO0816")
b.to_dict()

list[str]

{'name': 'ls',
 'value': ['1', 'a'],
 'unit': '-',
 'dtype': 'list',
 'description': '',
 'label': '',
 'required': False,
 'ontology': 'BFO0816'}

create a full qualified Attribute

In [6]:
value = [1, "c"]
print(sdata.Attribute.guess_dtype(value))
b = sdata.Attribute("ls", value, dtype="list")
b.to_dict()

list[str]

{'name': 'ls',
 'value': ['1', 'c'],
 'unit': '-',
 'dtype': 'list',
 'description': '',
 'label': '',
 'required': False,
 'ontology': ''}

In [7]:
fx = sdata.Attribute("force_x", value=1.2, unit="kN", dtype="float", description="force in x-direction")
fx

(Attr'force_x':1.2(float))

add Attribute to metadata

In [8]:
fx.dtype

'float'

In [28]:
m = sdata.Metadata(name="m1")
m.add(fx)
m.add(a)
m.add(b)
m.attributes

SortedDict({'force_x': (Attr'force_x':1.2(float)), 'ls': (Attr'ls':['1', 'c'](list)), 'otto1': (Attr'otto1':1(int))})

In [29]:
m.add("Fy", value=3.1, unit="N", dtype="float", description="force in y-direction", prefix="Load/")
m.attributes

SortedDict({'Load/Fy': (Attr'Fy':3.1(float)), 'force_x': (Attr'force_x':1.2(float)), 'ls': (Attr'ls':['1', 'c'](list)), 'otto1': (Attr'otto1':1(int))})

In [35]:
m.df

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
Fy,Fy,3.1,N,float,force in y-direction,,False,
force_x,force_x,1.2,kN,float,force in x-direction,,False,
ls,ls,"[1, c]",-,list,,,False,
otto1,otto1,1,-,int,,,False,BFO0815

In [39]:
sdata.Metadata.from_json(m.to_json()).df

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
Fy,Fy,3.1,N,float,force in y-direction,,False,
force_x,force_x,1.2,kN,float,force in x-direction,,False,
ls,ls,"[1, c]",-,list,,,False,
otto1,otto1,1,-,int,,,False,BFO0815

In [36]:
m.keys()

['Load/Fy', 'force_x', 'ls', 'otto1']

In [33]:
m.get('Load/Fy')

(Attr'Fy':3.1(float))

In [34]:
m.get('Fy')

(Attr'Fy':None(str))

In [32]:
m["otto1"].to_dict()

{'name': 'otto1',
 'value': 1,
 'unit': '-',
 'dtype': 'int',
 'description': '',
 'label': '',
 'required': False,
 'ontology': 'BFO0815'}

In [18]:
m.df

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
Fy,Fy,3.1,N,float,force in y-direction,,False,
force_x,force_x,1.2,kN,float,force in x-direction,,False,
ls,ls,"[1, c]",-,list,,,False,
otto1,otto1,1,-,int,,,False,BFO0815

In [13]:
mdict = m.to_dict()
mdict

{'force_x': {'name': 'force_x',
  'value': 1.2,
  'unit': 'kN',
  'dtype': 'float',
  'description': 'force in x-direction',
  'label': '',
  'required': False,
  'ontology': ''},
 'ls': {'name': 'ls',
  'value': ['1', 'c'],
  'unit': '-',
  'dtype': 'list',
  'description': '',
  'label': '',
  'required': False,
  'ontology': ''},
 'otto1': {'name': 'otto1',
  'value': 1,
  'unit': '-',
  'dtype': 'int',
  'description': '',
  'label': '',
  'required': False,
  'ontology': 'BFO0815'}}

In [15]:
sdata.Metadata.from_dict(mdict).df

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
force_x,force_x,1.2,kN,float,force in x-direction,,False,
ls,ls,"[1, c]",-,list,,,False,
otto1,otto1,1,-,int,,,False,BFO0815

In [63]:
b

(Attr'ls':['1', 'c'](list))


## Working with Attributes

In [ ]:
m["a"] = 1

In [ ]:
m["a"] = 1
m["b"] = 2.1
m["o"] = "c"
m.df

In [ ]:
for a in m:
    print(a)

In [ ]:
[a.value for k, a in m]

In [ ]:
m["b"].value

In [ ]:
m.pop("a")

In [ ]:
"a" in m

In [ ]:
m.get("a")

In [ ]:
m["a"] = a
m.df

In [ ]:
m["force_y"]

In [ ]:
m["force_x"]

In [ ]:
m.get("force_z") # not available -> None

In [ ]:
my_fx = m.get("force_x")
my_fx

In [ ]:
my_fy = m.get("force_y")
my_fy

In [ ]:
my_fx.value

In [ ]:
print("The {0.name} is {0.value} {0.unit}.".format(my_fx))
print("The {0.name} is {0.value} {0.unit}.".format(my_fy))

In [ ]:
my_fx.to_list()

In [ ]:
my_fx.to_dict()

In [ ]:
my_fx.to_csv(prefix="#$", sep=";")

## working with Metadata

In [ ]:
m.keys()

In [ ]:
m.values()

In [ ]:
m.items()

In [ ]:
m.to_dict()

In [ ]:
m.to_dict()

In [ ]:
m.to_dataframe()

### json IO

In [ ]:
print(m.to_csv(filepath=None))

In [ ]:
print(m.to_csv_header(prefix="##", sep="\t"))

In [ ]:
jsonfilepath = "/tmp/m.json"
print(m.to_json(filepath=jsonfilepath))

In [ ]:
json_str = """{"force_x": {"name": "force_x", "value": 1.2, "unit": "kN", "dtype": "float", "description": "force in x-direction"}, "force_y": {"name": "force_y", "value": 3.1, "unit": "N", "dtype": "float", "description": "force in y-direction"}}"""
m_json = sdata.Metadata.from_json(json_str)
m_json.df

In [ ]:
m_jsonfile = sdata.Metadata.from_json(filepath=jsonfilepath)
m_jsonfile.df

### list IO

In [ ]:
m.to_list()

In [ ]:
m2 = sdata.Metadata.from_list([['force_x', 1.2, 'float', 'kN', 'force in x-direction'],
 ['force_y', 3.1, 'float', 'N', 'force in y-direction'],["a",2], ["2"]])
m2.df

In [ ]:
m.df.loc["force_x", "value"]

In [ ]:
m.df.loc[:, "value"]

In [ ]:
c=sdata.Attribute("a_bool", True, dtype="bool", description="a boolean")
c.to_list()

In [ ]:
m = sdata.Metadata.from_dict({"a":"1", "b":1.1})
m.df

In [ ]:
m.to_dict()

In [ ]:
import datetime
datetime.datetime.now().strftime("%d.%m.%Y")

In [ ]:
l = m.to_list()
m.from_list(l)

In [ ]:
m.to_list()

In [ ]:
m.df.values.tolist()

In [ ]:
pd.DataFrame.from_records(m.df.values.tolist())

In [ ]:
df = pd.DataFrame.from_records(m.df.values.tolist(), columns=m.df.columns)
df

In [ ]:
df.to_clipboard()

In [ ]:
pd.read_clipboard()

In [ ]:
for x in [['force_x', 1.2, 'float', 'kN', 'force in x-direction'],
 ['force_y', 3.1, 'float', 'N', 'force in y-direction']]:
    print(x)

In [ ]:
m.to_dict()

In [ ]:
md = m.from_dict({'force_x': {'name': 'force_x',
  'value': 1.2,
  'unit': 'kN',
  'dtype': 'float',
  'description': 'force in x-direction'},
 'force_y': {'name': 'force_y',
  'value': 3.1,
  'description': 'force in y-direction'},
  'force_y': {'name': 'force_z',
  'value': 3.1,
  'description': 'force in y-direction'}})
md.df

In [ ]:
m = sdata.Metadata.from_list([["a",2], 
                              ["!sdata_name", "hallo"], 
                              ["Temperature T [degC]", 23, "°C", "float"],
                              ["force F [kN]", 1.23, "kN"]
                             ])
m.df

In [ ]:
m.set_unit_from_name()
m.df

In [ ]:
m.attributes

In [ ]:
m.user_attributes

In [ ]:
m.sdata_attributes

In [ ]:
m = sdata.Metadata.from_list([["a",2], 
                              ["!sdata_name", "hallo"], 
                              ["Temperature T [degC]", "23", "str"],
                              ["force F [kN]", "1.23", "str"]
                             ])
m.df

In [ ]:
m.guess_value_dtype()
m.df

In [ ]:
m.to_dict()

In [ ]:
filepath = "/tmp/metadata.csv"
m.add("foo", 123)
m.to_csv(filepath)
m5 = sdata.metadata.Metadata.from_csv(filepath)
print("m5", m5.to_dict())
assert m.get_attr("foo").name==m5.get_attr("foo").name
assert m.get_attr("foo").value==m5.get_attr("foo").value

In [ ]:
m.sha3_256, m5.sha3_256

In [ ]:
m5.df

In [ ]:
m.df

In [ ]:
df = m5.df
df.fillna("", inplace=True)
df.replace("nan", "", inplace=True)
df

In [ ]:
m5.df.description.values[0]

In [42]:
m.to_dict()

{'Fy': {'name': 'Fy',
  'value': 3.1,
  'unit': 'N',
  'dtype': 'float',
  'description': 'force in y-direction',
  'label': '',
  'required': False,
  'ontology': ''},
 'force_x': {'name': 'force_x',
  'value': 1.2,
  'unit': 'kN',
  'dtype': 'float',
  'description': 'force in x-direction',
  'label': '',
  'required': False,
  'ontology': ''},
 'ls': {'name': 'ls',
  'value': ['1', 'c'],
  'unit': '-',
  'dtype': 'list',
  'description': '',
  'label': '',
  'required': False,
  'ontology': ''},
 'otto1': {'name': 'otto1',
  'value': 1,
  'unit': '-',
  'dtype': 'int',
  'description': '',
  'label': '',
  'required': False,
  'ontology': 'BFO0815'}}

In [44]:
m.user_attributes

SortedDict({'Fy': (Attr'Fy':3.1(float)), 'force_x': (Attr'force_x':1.2(float)), 'ls': (Attr'ls':['1', 'c'](list)), 'otto1': (Attr'otto1':1(int))})

In [53]:
sdata.SUUID(class_name="Project", name="xyz", )

(Project__xyz__45164a9c108a4bc4aad77298ab3f5380)

In [62]:
sdata.SUUID.from_name(class_name="Project", name="xyz", ns_name="!").sname

'Project__xyz__af5b3de7387f56c1ad8685f5c43fd7f2'