In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib notebook
%autosave 0
    
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

import os
import sys
import numpy as np
import pandas as pd
import sdata
import sdata.sclass

11:22:12 INFO:Note: NumExpr detected 22 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
11:22:12 INFO:NumExpr defaulting to 16 threads.

Autosave disabled

In [2]:
df = pd.DataFrame({"a": [1., 2.], "b": ["a", "b"], "c": [4, 5]})
print(df.dtypes)
df

a    float64
b     object
c      int64
dtype: object

     a  b  c
0  1.0  a  4
1  2.0  b  5

In [3]:
project = sdata.SUUID.from_name(class_name="Project", name="My_Project")
project

In [4]:
column_metadata = sdata.Metadata(name="column_metadata")
column_metadata.add("a", unit="mm", description="Länge a", label="$a$", required=True, ontology="qudt:Length")

sdf = sdata.sclass.DataFrame(name="my dataframe with metadata", df=df, project=project,
                            column_metadata=column_metadata)
print(sdf)
sdf.cmdf

<DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95>

    name    value unit dtype description label  required     ontology
key
a      a  float64   mm   str     Länge a   $a$      True  qudt:Length
b      b   object    -   str                       False
c      c    int64    -   str                       False

In [5]:
sdf.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.dataframe.DataFrame:DataFrame,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.291300+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,my dataframe with metadata,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__my_project__df19da75fb625c189784b53d7...,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,DataFrame__my_dataframe_with_metadata__c21bea2...,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [6]:
sdf.cmdf

    name    value unit dtype description label  required     ontology
key
a      a  float64   mm   str     Länge a   $a$      True  qudt:Length
b      b   object    -   str                       False
c      c    int64    -   str                       False

In [7]:
parquet_bytes = sdf.to_parquet(compression="zstd")
print(len(parquet_bytes))
parquet_bytes[:30]

7715

b'PAR1\x15\x04\x15 \x152L\x15\x04\x15\x00\x12\x00\x00(\xb5/\xfd \x10\x81\x00\x00\x00\x00\x00'

In [8]:
sdf2 = sdata.sclass.DataFrame.from_parquet_bytes(parquet_bytes)
sdf2.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.dataframe.DataFrame:DataFrame,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.291300+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,my dataframe with metadata,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__my_project__df19da75fb625c189784b53d7...,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,DataFrame__my_dataframe_with_metadata__c21bea2...,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [9]:
sdf2.cmdf

    name    value unit dtype description label  required     ontology
key
a      a  float64   mm   str     Länge a   $a$      True  qudt:Length
b      b   object    -   str                       False
c      c    int64    -   str                       False

In [10]:
filepath = sdf.to_parquet(path="/tmp")
filepath

11:22:12 INFO:DataFrame Parquet saved to /tmp/DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95.spq

'/tmp/DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95.spq'

In [11]:
sdf3 = sdata.sclass.DataFrame.from_parquet(filepath)
sdf3.mdf

11:22:12 INFO:<DataFrame__tmp_dataframe_my_dataframe_with_metadata_c21bea2397d054d9863913c39debfe95_spq__408fbba9c4874de1b59a95eb5400eb3e>

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.dataframe.DataFrame:DataFrame,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.291300+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,my dataframe with metadata,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__my_project__df19da75fb625c189784b53d7...,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,DataFrame__my_dataframe_with_metadata__c21bea2...,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [12]:
sdf3.cmdf

    name    value unit dtype description label  required     ontology
key
a      a  float64   mm   str     Länge a   $a$      True  qudt:Length
b      b   object    -   str                       False
c      c    int64    -   str                       False

In [13]:
sdf.to_dict()

{'metadata': {'_sdata_class': {'name': '_sdata_class',
   'value': 'sdata.sclass.dataframe.DataFrame:DataFrame',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata class',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_ctime': {'name': '_sdata_ctime',
   'value': '2025-09-29T11:22:12.291300+00:00',
   'unit': '-',
   'dtype': 'str',
   'description': 'UTC creation date',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_name': {'name': '_sdata_name',
   'value': 'my dataframe with metadata',
   'unit': '-',
   'dtype': 'str',
   'description': 'name of the data object',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_parent_sname': {'name': '_sdata_parent_sname',
   'value': '',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the parent',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_project_sname': {'name': '_sdata_project_sname',
   'value': 'Project__my_project__df19da75fb625c189784b53d7618fab3',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the project',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_sname': {'name': '_sdata_sname',
   'value': 'DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the data object',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_topology_class': {'name': '_sdata_topology_class',
   'value': 'sdata.sclass:IndependentContinuant',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata topology class name',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_version': {'name': '_sdata_version',
   'value': '1.0.0',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata package version',
   'label': '',
   'required': True,
   'ontology': ''}},
 'data': {'parquet_bytes': 'UEFSMRUEFSAVJEwVBBUAEgAAEDwAAAAAAADwPwAAAAAAAABAFQAVEhUWLBUEFRAVBhUGHBgIAAAAAAAAAEAYCAAAAAAAAPA/FgAoCAAAAAAAAABAGAgAAAAAAADwPwAAAAkgAgAAAAQBAQMCFQQVFBUYTBUEFQASAAAKJAEAAABhAQAAAGIVABUSFRYsFQQVEBUGFQYcNgAoAWIYAWEAAAAJIAIAAAAEAQEDAhUEFSAVJEwVBBUAEgAAEDwEAAAAAAAAAAUAAAAAAAAAFQAVEhUWLBUEFRAVBhUGHBgIBQAAAAAAAAAYCAQAAAAAAAAAFgAoCAUAAAAAAAAAGAgEAAAAAAAAAAAAAAkgAgAAAAQBAQMCFQQZTDUAGAZzY2hlbWEVBgAVCiUCGAFhABUMJQIYAWIlAEwcAAAAFQQlAhgBYwAWBBkcGTwmABwVChk1AAYQGRgBYRUCFgQWyAEW0AEmSCYIHBgIAAAAAAAAAEAYCAAAAAAAAPA/FgAoCAAAAAAAAABAGAgAAAAAAADwPwAZLBUEFQAVAgAVABUQFQIAPCkGGSYABAAAACYAHBUMGTUABhAZGAFiFQIWBBZ4FoABJowCJtgBHDYAKAFiGAFhABksFQQVABUCABUAFRAVAgA8FgQZBhkmAAQAAAAmABwVBBk1AAYQGRgBYxUCFgQWyAEW0AEmmAMm2AIcGAgFAAAAAAAAABgIBAAAAAAAAAAWACgIBQAAAAAAAAAYCAQAAAAAAAAAABksFQQVABUCABUAFRAVAgA8KQYZJgAEAAAAFogEFgQmCBagBAAZLBgGcGFuZGFzGPYEeyJpbmRleF9jb2x1bW5zIjogW3sia2luZCI6ICJyYW5nZSIsICJuYW1lIjogImluZGV4IiwgInN0YXJ0IjogMCwgInN0b3AiOiAyLCAic3RlcCI6IDF9XSwgImNvbHVtbl9pbmRleGVzIjogW3sibmFtZSI6IG51bGwsICJmaWVsZF9uYW1lIjogbnVsbCwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiB7ImVuY29kaW5nIjogIlVURi04In19XSwgImNvbHVtbnMiOiBbeyJuYW1lIjogImEiLCAiZmllbGRfbmFtZSI6ICJhIiwgInBhbmRhc190eXBlIjogImZsb2F0NjQiLCAibnVtcHlfdHlwZSI6ICJmbG9hdDY0IiwgIm1ldGFkYXRhIjogbnVsbH0sIHsibmFtZSI6ICJiIiwgImZpZWxkX25hbWUiOiAiYiIsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogbnVsbH0sIHsibmFtZSI6ICJjIiwgImZpZWxkX25hbWUiOiAiYyIsICJwYW5kYXNfdHlwZSI6ICJpbnQ2NCIsICJudW1weV90eXBlIjogImludDY0IiwgIm1ldGFkYXRhIjogbnVsbH1dLCAiY3JlYXRvciI6IHsibGlicmFyeSI6ICJweWFycm93IiwgInZlcnNpb24iOiAiMjEuMC4wIn0sICJwYW5kYXNfdmVyc2lvbiI6ICIyLjMuMiJ9ABgMQVJST1c6c2NoZW1hGLgJLy8vLy80QURBQUFRQUFBQUFBQUtBQTRBQmdBRkFBZ0FDZ0FBQUFBQkJBQVFBQUFBQUFBS0FBd0FBQUFFQUFnQUNnQUFBS3dDQUFBRUFBQUFBUUFBQUF3QUFBQUlBQXdBQkFBSUFBZ0FBQUNFQWdBQUJBQUFBSFlDQUFCN0ltbHVaR1Y0WDJOdmJIVnRibk1pT2lCYmV5SnJhVzVrSWpvZ0luSmhibWRsSWl3Z0ltNWhiV1VpT2lBaWFXNWtaWGdpTENBaWMzUmhjblFpT2lBd0xDQWljM1J2Y0NJNklESXNJQ0p6ZEdWd0lqb2dNWDFkTENBaVkyOXNkVzF1WDJsdVpHVjRaWE1pT2lCYmV5SnVZVzFsSWpvZ2JuVnNiQ3dnSW1acFpXeGtYMjVoYldVaU9pQnVkV3hzTENBaWNHRnVaR0Z6WDNSNWNHVWlPaUFpZFc1cFkyOWtaU0lzSUNKdWRXMXdlVjkwZVhCbElqb2dJbTlpYW1WamRDSXNJQ0p0WlhSaFpHRjBZU0k2SUhzaVpXNWpiMlJwYm1jaU9pQWlWVlJHTFRnaWZYMWRMQ0FpWTI5c2RXMXVjeUk2SUZ0N0ltNWhiV1VpT2lBaVlTSXNJQ0ptYVdWc1pGOXVZVzFsSWpvZ0ltRWlMQ0FpY0dGdVpHRnpYM1I1Y0dVaU9pQWlabXh2WVhRMk5DSXNJQ0p1ZFcxd2VWOTBlWEJsSWpvZ0ltWnNiMkYwTmpRaUxDQWliV1YwWVdSaGRHRWlPaUJ1ZFd4c2ZTd2dleUp1WVcxbElqb2dJbUlpTENBaVptbGxiR1JmYm1GdFpTSTZJQ0ppSWl3Z0luQmhibVJoYzE5MGVYQmxJam9nSW5WdWFXTnZaR1VpTENBaWJuVnRjSGxmZEhsd1pTSTZJQ0p2WW1wbFkzUWlMQ0FpYldWMFlXUmhkR0VpT2lCdWRXeHNmU3dnZXlKdVlXMWxJam9nSW1NaUxDQWlabWxsYkdSZmJtRnRaU0k2SUNKaklpd2dJbkJoYm1SaGMxOTBlWEJsSWpvZ0ltbHVkRFkwSWl3Z0ltNTFiWEI1WDNSNWNHVWlPaUFpYVc1ME5qUWlMQ0FpYldWMFlXUmhkR0VpT2lCdWRXeHNmVjBzSUNKamNtVmhkRzl5SWpvZ2V5SnNhV0p5WVhKNUlqb2dJbkI1WVhKeWIzY2lMQ0FpZG1WeWMybHZiaUk2SUNJeU1TNHdMakFpZlN3Z0luQmhibVJoYzE5MlpYSnphVzl1SWpvZ0lqSXVNeTR5SW4wQUFBWUFBQUJ3WVc1a1lYTUFBQU1BQUFCNEFBQUFQQUFBQUFRQUFBQ2svLy8vQUFBQkFoQUFBQUFjQUFBQUJBQUFBQUFBQUFBQkFBQUFZd0FBQUFnQURBQUlBQWNBQ0FBQUFBQUFBQUZBQUFBQTJQLy8vd0FBQVFVUUFBQUFHQUFBQUFRQUFBQUFBQUFBQVFBQUFHSUFBQUFFQUFRQUJBQUFBQkFBRkFBSUFBWUFCd0FNQUFBQUVBQVFBQUFBQUFBQkF4QUFBQUFZQUFBQUJBQUFBQUFBQUFBQkFBQUFZUUFHQUFnQUJnQUdBQUFBQUFBQ0FBPT0AGCBwYXJxdWV0LWNwcC1hcnJvdyB2ZXJzaW9uIDIxLjAuMBk8HAAAHAAAHAAAAMUIAABQQVIx',
  'column_metadata': {'a': {'name': 'a',
    'value': 'float64',
    'unit': 'mm',
    'dtype': 'str',
    'description': 'Länge a',
    'label': '$a$',
    'required': True,
    'ontology': 'qudt:Length'},
   'b': {'name': 'b',
    'value': 'object',
    'unit': '-',
    'dtype': 'str',
    'description': '',
    'label': '',
    'required': False,
    'ontology': ''},
   'c': {'name': 'c',
    'value': 'int64',
    'unit': '-',
    'dtype': 'str',
    'description': '',
    'label': '',
    'required': False,
    'ontology': ''}}},
 'description': ''}

In [14]:
print(sdf.sname)
s2 = sdata.sclass.DataFrame.from_dict(sdf.to_dict())
print(s2.sname)
s2.mdf

DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95
DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.dataframe.DataFrame:DataFrame,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.291300+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,my dataframe with metadata,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__my_project__df19da75fb625c189784b53d7...,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,DataFrame__my_dataframe_with_metadata__c21bea2...,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [15]:
s2.cmdf

    name    value unit dtype description label  required     ontology
key
a      a  float64   mm   str     Länge a   $a$      True  qudt:Length
b      b   object    -   str                       False
c      c    int64    -   str                       False

In [16]:
sdf0 = sdata.sclass.DataFrame(name="a")
sdf0.to_dict()

{'metadata': {'_sdata_class': {'name': '_sdata_class',
   'value': 'sdata.sclass.dataframe.DataFrame:DataFrame',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata class',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_ctime': {'name': '_sdata_ctime',
   'value': '2025-09-29T11:22:12.452870+00:00',
   'unit': '-',
   'dtype': 'str',
   'description': 'UTC creation date',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_name': {'name': '_sdata_name',
   'value': 'a',
   'unit': '-',
   'dtype': 'str',
   'description': 'name of the data object',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_parent_sname': {'name': '_sdata_parent_sname',
   'value': '',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the parent',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_project_sname': {'name': '_sdata_project_sname',
   'value': '',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the project',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_sname': {'name': '_sdata_sname',
   'value': 'DataFrame__a__27e5a78dba124027a52aa1747d0847f5',
   'unit': '-',
   'dtype': 'str',
   'description': 'sname of the data object',
   'label': '',
   'required': True,
   'ontology': ''},
  '_sdata_topology_class': {'name': '_sdata_topology_class',
   'value': 'sdata.sclass:IndependentContinuant',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata topology class name',
   'label': '',
   'required': False,
   'ontology': ''},
  '_sdata_version': {'name': '_sdata_version',
   'value': '1.0.0',
   'unit': '-',
   'dtype': 'str',
   'description': 'sdata package version',
   'label': '',
   'required': True,
   'ontology': ''}},
 'data': {'parquet_bytes': 'UEFSMRUEGRw1ABgGc2NoZW1hFQAAFgAZHBkMFgAWACYAFgAAGSwYBnBhbmRhcxi0AnsiaW5kZXhfY29sdW1ucyI6IFt7ImtpbmQiOiAicmFuZ2UiLCAibmFtZSI6ICJpbmRleCIsICJzdGFydCI6IDAsICJzdG9wIjogMCwgInN0ZXAiOiAxfV0sICJjb2x1bW5faW5kZXhlcyI6IFt7Im5hbWUiOiBudWxsLCAiZmllbGRfbmFtZSI6IG51bGwsICJwYW5kYXNfdHlwZSI6ICJpbnQ2NCIsICJudW1weV90eXBlIjogImludDY0IiwgIm1ldGFkYXRhIjogbnVsbH1dLCAiY29sdW1ucyI6IFtdLCAiY3JlYXRvciI6IHsibGlicmFyeSI6ICJweWFycm93IiwgInZlcnNpb24iOiAiMjEuMC4wIn0sICJwYW5kYXNfdmVyc2lvbiI6ICIyLjMuMiJ9ABgMQVJST1c6c2NoZW1hGLgELy8vLy82QUJBQUFRQUFBQUFBQUtBQTRBQmdBRkFBZ0FDZ0FBQUFBQkJBQVFBQUFBQUFBS0FBd0FBQUFFQUFnQUNnQUFBR3dCQUFBRUFBQUFBUUFBQUF3QUFBQUlBQXdBQkFBSUFBZ0FBQUJFQVFBQUJBQUFBRFFCQUFCN0ltbHVaR1Y0WDJOdmJIVnRibk1pT2lCYmV5SnJhVzVrSWpvZ0luSmhibWRsSWl3Z0ltNWhiV1VpT2lBaWFXNWtaWGdpTENBaWMzUmhjblFpT2lBd0xDQWljM1J2Y0NJNklEQXNJQ0p6ZEdWd0lqb2dNWDFkTENBaVkyOXNkVzF1WDJsdVpHVjRaWE1pT2lCYmV5SnVZVzFsSWpvZ2JuVnNiQ3dnSW1acFpXeGtYMjVoYldVaU9pQnVkV3hzTENBaWNHRnVaR0Z6WDNSNWNHVWlPaUFpYVc1ME5qUWlMQ0FpYm5WdGNIbGZkSGx3WlNJNklDSnBiblEyTkNJc0lDSnRaWFJoWkdGMFlTSTZJRzUxYkd4OVhTd2dJbU52YkhWdGJuTWlPaUJiWFN3Z0ltTnlaV0YwYjNJaU9pQjdJbXhwWW5KaGNua2lPaUFpY0hsaGNuSnZkeUlzSUNKMlpYSnphVzl1SWpvZ0lqSXhMakF1TUNKOUxDQWljR0Z1WkdGelgzWmxjbk5wYjI0aU9pQWlNaTR6TGpJaWZRQUFBQUFHQUFBQWNHRnVaR0Z6QUFBQUFBQUFBQUFBQUE9PQAYIHBhcnF1ZXQtY3BwLWFycm93IHZlcnNpb24gMjEuMC4wGQwA0QMAAFBBUjE=',
  'column_metadata': {}},
 'description': ''}

In [17]:
sdf.to_zip(filepath=f"/tmp/{sdf.sname}.zip")

In [18]:
f"/tmp/{sdf.sname}.zip"

'/tmp/DataFrame__my_dataframe_with_metadata__c21bea2397d054d9863913c39debfe95.zip'

In [19]:
sdata.DataFrame.from_zip(f"/tmp/{sdf.sname}.zip").mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.dataframe.DataFrame:DataFrame,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.291300+00:00,-,str,UTC creation date,,False,
_sdata_name,_sdata_name,my dataframe with metadata,-,str,name of the data object,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,Project__my_project__df19da75fb625c189784b53d7...,-,str,sname of the project,,False,
_sdata_sname,_sdata_sname,DataFrame__my_dataframe_with_metadata__c21bea2...,-,str,sname of the data object,,True,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,

In [20]:
fr = sdata.sclass.FileReference.from_file("simple.png")
fr.to_zip(f"/tmp/{fr.sname}.zip")

In [21]:
fr.mdf

,name,value,unit,dtype,description,label,required,ontology
key,,,,,,,,
_sdata_class,_sdata_class,sdata.sclass.filereference.FileReference:FileR...,-,str,sdata class,,True,
_sdata_ctime,_sdata_ctime,2025-09-29T11:22:12.494214+00:00,-,str,UTC creation date,,False,
_sdata_filectime,_sdata_filectime,2024-12-20 09:45:52.109289+00:00,-,str,UTC file creation date,,False,
_sdata_filesize,_sdata_filesize,7962,-,int,file size in bytes,,False,
_sdata_filetype,_sdata_filetype,.png,-,str,file suffix,,False,
_sdata_name,_sdata_name,simple.png,-,str,base name of the file without folder,,True,
_sdata_parent_sname,_sdata_parent_sname,,-,str,sname of the parent,,False,
_sdata_project_sname,_sdata_project_sname,,-,str,sname of the project,,False,
_sdata_sha3_256,_sdata_sha3_256,ee017cc908c8966037afffb43f8769a0a2d47f554a756a...,-,str,SHA-3-256,,False,
_sdata_sname,_sdata_sname,FileReference__simple_png__c82e79549c7f53baa16...,-,str,sname of the data object,,True,
_sdata_stem,_sdata_stem,simple,-,str,file name without suffix,,False,
_sdata_topology_class,_sdata_topology_class,sdata.sclass:IndependentContinuant,-,str,sdata topology class name,,False,
_sdata_version,_sdata_version,1.0.0,-,str,sdata package version,,True,