In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%autosave 0
    
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

import os
import sys
import numpy as np
import pandas as pd
import sdata
import uuid
print("sdata v{}".format(sdata.__version__))

Autosave disabled

04:48:23 DEBUG:Loaded backend module://ipykernel.pylab.backend_inline version unknown.

sdata v0.10.1

In [2]:
attr = sdata.metadata.Attribute("a",1)
attr

(Attr'a':1(int))

In [3]:
attrschema = sdata.metadata.AttributeSchema("a",1)
attrschema

(AttrSchema'a':False(int))

In [4]:
metadataschema = sdata.metadata.MetadataSchema()
metadataschema.add(attrschema)

In [5]:
metadataschema.to_dict()

{'sdata_version': {'name': 'sdata_version',
  'value': '0.10.1',
  'unit': '-',
  'dtype': 'str',
  'description': '',
  'label': '',
  'required': False},
 'a': {'name': 'a',
  'value': 1,
  'unit': '-',
  'dtype': 'int',
  'description': '',
  'label': '',
  'required': False}}

In [6]:
metadataschema.df

                        name   value dtype unit description label  required
key
sdata_version  sdata_version  0.10.1   str    -                       False
a                          a       1   int    -                       False

In [7]:
d = metadataschema.to_dict()
df = pd.DataFrame(columns=metadataschema.ATTRIBUTEKEYS)
df
df = pd.DataFrame.from_dict(d, orient="index")
# df[metadataschema.ATTRIBUTEKEYS]
df

                        name   value unit dtype description label  required
sdata_version  sdata_version  0.10.1    -   str                       False
a                          a       1    -   int                       False

In [8]:
metadataschema.ATTRIBUTEKEYS

['name', 'value', 'dtype', 'unit', 'description', 'label', 'required']

In [9]:
metadataschema.add("a", required=1)
metadataschema.df

                        name   value dtype unit description label  required
key
sdata_version  sdata_version  0.10.1   str    -                       False
a                          a       1   int    -                        True

In [10]:
schema = sdata.Schema(name="Mein Schema")
schema.metadata.df

,name,value,dtype,unit,description,label,required
key,,,,,,,
sdata_version,sdata_version,0.10.1,str,-,,,False
name,name,Mein Schema,str,-,,,False
uuid,uuid,10aeed7ed2a04475b5d1b61ac2e48aa7,str,-,,,False

In [11]:
schema.copy()

(Schema 'Mein Schema':ad5fdd9934294f48acc697b302422804)

In [12]:
js = '{"metadata": {"sdata_version": {"name": "sdata_version", "value": "0.10.1", "unit": "", "dtype": "str", "description": "", "label": ""}, "name": {"name": "name", "value": "MedMnSteel_10mps_1_RD", "unit": "-", "dtype": "str", "description": "", "label": "10mps(1)-RD"}, "uuid": {"name": "uuid", "value": "2b8fe212a41a30a4955f869cfdde046c", "unit": "-", "dtype": "str", "description": "", "label": ""}, "Test Name": {"name": "Test Name", "value": "10mps(1)", "unit": "", "dtype": "str", "description": "", "label": ""}, "Material": {"name": "Material", "value": "Med Mn Steel", "unit": "", "dtype": "str", "description": "", "label": ""}, "Thickness": {"name": "Thickness", "value": 1.25, "unit": "mm", "dtype": "float", "description": "", "label": ""}, "Width": {"name": "Width", "value": 7.43, "unit": "mm", "dtype": "float", "description": "", "label": ""}, "Gauge Length": {"name": "Gauge Length", "value": 20.0, "unit": "mm", "dtype": "float", "description": "", "label": ""}, "Target Strain Rate": {"name": "Target Strain Rate", "value": 500.0, "unit": "1/s", "dtype": "float", "description": "", "label": ""}, "Orientation": {"name": "Orientation", "value": "RD", "unit": "", "dtype": "str", "description": "", "label": ""}, "License": {"name": "License", "value": "Creative Commons Lizenz", "unit": "-", "dtype": "str", "description": "", "label": ""}, "Source": {"name": "Source", "value": "https://materialsdata.nist.gov/handle/11256/823", "unit": "-", "dtype": "str", "description": "", "label": ""}, "sdata_date": {"name": "sdata_date", "value": "2020-12-10T00:00:00+00:00", "unit": "-", "dtype": "str", "description": "", "label": ""}}, "table": {"Time (s)": {"0": 0.0, "1": 5e-05, "2": 0.0001, "3": 0.00015, "4": 0.0002, "5": 0.00025, "6": 0.0003, "7": 0.00035, "8": 0.0004, "9": 0.00045, "10": 0.0005, "11": 0.00055, "12": 0.0006, "13": 0.00065, "14": 0.0007, "15": 0.00075, "16": 0.0008, "17": 0.00085, "18": 0.0009, "19": 0.00095, "20": 0.001, "21": 0.00105, "22": 0.0011}, "Extension (mm)": {"0": 0.0, "1": 0.000137871, "2": 0.00108363, "3": 0.00685899, "4": 0.00874933, "5": 0.017484, "6": 0.0325352, "7": 0.0590194, "8": 0.182078, "9": 0.559806, "10": 1.05668, "11": 1.53519, "12": 1.95234, "13": 2.45937, "14": 2.96673, "15": 3.49238, "16": 4.02158, "17": 4.55764, "18": 5.06491, "19": 5.5959, "20": 6.15847, "21": 6.74382, "22": 7.48598}, "Load (kN)": {"0": -0.3464563814634145, "1": -0.30985491804878035, "2": -0.32981772292682915, "3": -0.14017645463414616, "4": 0.5318799892682929, "5": 1.3370152770731711, "6": 2.4482430819512198, "7": 4.720591618536586, "8": 8.02764088682927, "9": 8.583270155121953, "10": 7.485328691707317, "11": 8.290489179512196, "12": 8.223929423414635, "13": 8.732948935609759, "14": 8.530001862439025, "15": 8.88601332585366, "16": 8.965859423414635, "17": 8.98913869170732, "18": 8.94924893560976, "19": 8.935896008780489, "20": 8.822787960000003, "21": 8.553301618536587, "22": 8.297152838048781}, "Engineering Strain": {"0": 0.0, "1": 8.10858e-06, "2": 6.37312e-05, "3": 0.000403397, "4": 0.000514572, "5": 0.00102828, "6": 0.00191349, "7": 0.0034711, "8": 0.0107085, "9": 0.0329238, "10": 0.0621462, "11": 0.0902891, "12": 0.114822, "13": 0.144642, "14": 0.174481, "15": 0.205396, "16": 0.23652, "17": 0.268048, "18": 0.297882, "19": 0.329111, "20": 0.362197, "21": 0.396623, "22": 0.440271}, "Engineering Stress (MPa)": {"0": -31.51045, "1": -44.92826, "2": -35.57331, "3": -9.35123, "4": 52.44761, "5": 137.66427, "6": 272.66403, "7": 542.04902, "8": 819.27482, "9": 901.48198, "10": 864.39066, "11": 853.68431, "12": 910.72353, "13": 916.67848, "14": 937.87568, "15": 947.03726, "16": 967.45605, "17": 966.98613, "18": 965.57341, "19": 961.49926, "20": 947.87483, "21": 924.77565, "22": 891.8019}, "True Strain": {"0": 0.0, "1": 8.108547125753067e-06, "2": 6.372916925338195e-05, "3": 0.00040331565730497625, "4": 0.0005144396532276926, "5": 0.0010277516822622616, "6": 0.0019116616100423053, "7": 0.003465089636760603, "8": 0.010651570075978249, "9": 0.032393421685795294, "10": 0.060291578128247786, "11": 0.08644289043176238, "12": 0.1086947509124551, "13": 0.13509192436124148, "14": 0.16082634788934302, "15": 0.18680814366076975, "16": 0.21230098253514051, "17": 0.2374787101881459, "18": 0.2607337050585073, "19": 0.28451029768808184, "20": 0.3090988375028791, "21": 0.33405717986071115, "22": 0.36483129032600076}, "True Stress (MPa)": {"0": -31.51045, "1": -44.928624304390475, "2": -35.57557712973427, "3": -9.355002258128309, "4": 52.47459807157291, "5": 137.8058274155556, "6": 273.1857698947647, "7": 543.9305263533221, "8": 828.04802440997, "9": 931.1621924131241, "10": 918.1092548344919, "11": 930.7626980340209, "12": 1015.29462716166, "13": 1049.26868870416, "14": 1101.51716652208, "15": 1141.5549250549598, "16": 1196.2787549460002, "17": 1226.18482817424, "18": 1253.20034851762, "19": 1277.93924295786, "20": 1291.1922498015101, "21": 1291.56294262995, "22": 1284.4364143149}}, "description": ""}'

In [13]:
data = sdata.Data.from_json(js)
print(data)
print(data.metadata.keys())
data.df

(Data 'MedMnSteel_10mps_1_RD':2b8fe212a41a30a4955f869cfdde046c)
['sdata_version', 'name', 'uuid', 'Test Name', 'Material', 'Thickness', 'Width', 'Gauge Length', 'Target Strain Rate', 'Orientation', 'License', 'Source', 'sdata_date']

,Time (s),Extension (mm),Load (kN),Engineering Strain,Engineering Stress (MPa),True Strain,True Stress (MPa)
index,,,,,,,
0,0.00000,0.000000,-0.346456,0.000000,-31.51045,0.000000,-31.510450
1,0.00005,0.000138,-0.309855,0.000008,-44.92826,0.000008,-44.928624
2,0.00010,0.001084,-0.329818,0.000064,-35.57331,0.000064,-35.575577
3,0.00015,0.006859,-0.140176,0.000403,-9.35123,0.000403,-9.355002
4,0.00020,0.008749,0.531880,0.000515,52.44761,0.000514,52.474598
5,0.00025,0.017484,1.337015,0.001028,137.66427,0.001028,137.805827
6,0.00030,0.032535,2.448243,0.001913,272.66403,0.001912,273.185770
7,0.00035,0.059019,4.720592,0.003471,542.04902,0.003465,543.930526
8,0.00040,0.182078,8.027641,0.010708,819.27482,0.010652,828.048024
9,0.00045,0.559806,8.583270,0.032924,901.48198,0.032393,931.162192
10,0.00050,1.056680,7.485329,0.062146,864.39066,0.060292,918.109255
11,0.00055,1.535190,8.290489,0.090289,853.68431,0.086443,930.762698
12,0.00060,1.952340,8.223929,0.114822,910.72353,0.108695,1015.294627
13,0.00065,2.459370,8.732949,0.144642,916.67848,0.135092,1049.268689
14,0.00070,2.966730,8.530002,0.174481,937.87568,0.160826,1101.517167
15,0.00075,3.492380,8.886013,0.205396,947.03726,0.186808,1141.554925
16,0.00080,4.021580,8.965859,0.236520,967.45605,0.212301,1196.278755
17,0.00085,4.557640,8.989139,0.268048,966.98613,0.237479,1226.184828
18,0.00090,5.064910,8.949249,0.297882,965.57341,0.260734,1253.200349
19,0.00095,5.595900,8.935896,0.329111,961.49926,0.284510,1277.939243
20,0.00100,6.158470,8.822788,0.362197,947.87483,0.309099,1291.192250
21,0.00105,6.743820,8.553302,0.396623,924.77565,0.334057,1291.562943
22,0.00110,7.485980,8.297153,0.440271,891.80190,0.364831,1284.436414

In [14]:
data.metadata.df

,name,value,dtype,unit,description,label
key,,,,,,
sdata_version,sdata_version,0.10.1,str,,,
name,name,MedMnSteel_10mps_1_RD,str,-,,10mps(1)-RD
uuid,uuid,2b8fe212a41a30a4955f869cfdde046c,str,-,,
Test Name,Test Name,10mps(1),str,,,
Material,Material,Med Mn Steel,str,,,
Thickness,Thickness,1.25,float,mm,,
Width,Width,7.43,float,mm,,
Gauge Length,Gauge Length,20,float,mm,,
Target Strain Rate,Target Strain Rate,500,float,1/s,,
Orientation,Orientation,RD,str,,,
License,License,Creative Commons Lizenz,str,-,,
Source,Source,https://materialsdata.nist.gov/handle/11256/823,str,-,,
sdata_date,sdata_date,2020-12-10T00:00:00+00:00,str,-,,

In [15]:
data.metadata.relabel("!", "!!")

04:48:23 WARNING:<class 'sdata.metadata.Metadata'>: no Attribute ! to relabel.

In [16]:
data.metadata.relabel("Orientation", "orientation")

In [17]:
data.metadata.items()

[('sdata_version', (Attr'sdata_version':0.10.1(str))),
 ('name', (Attr'name':MedMnSteel_10mps_1_RD(str))),
 ('uuid', (Attr'uuid':2b8fe212a41a30a4955f869cfdde046c(str))),
 ('Test Name', (Attr'Test Name':10mps(1)(str))),
 ('Material', (Attr'Material':Med Mn Steel(str))),
 ('Thickness', (Attr'Thickness':1.25(float))),
 ('Width', (Attr'Width':7.43(float))),
 ('Gauge Length', (Attr'Gauge Length':20.0(float))),
 ('Target Strain Rate', (Attr'Target Strain Rate':500.0(float))),
 ('License', (Attr'License':Creative Commons Lizenz(str))),
 ('Source',
  (Attr'Source':https://materialsdata.nist.gov/handle/11256/823(str))),
 ('sdata_date', (Attr'sdata_date':2020-12-10T00:00:00+00:00(str))),
 ('orientation', (Attr'orientation':RD(str)))]

In [18]:
data.metadata.sort()

In [19]:
data.metadata.items()

[('Gauge Length', (Attr'Gauge Length':20.0(float))),
 ('License', (Attr'License':Creative Commons Lizenz(str))),
 ('Material', (Attr'Material':Med Mn Steel(str))),
 ('Source',
  (Attr'Source':https://materialsdata.nist.gov/handle/11256/823(str))),
 ('Target Strain Rate', (Attr'Target Strain Rate':500.0(float))),
 ('Test Name', (Attr'Test Name':10mps(1)(str))),
 ('Thickness', (Attr'Thickness':1.25(float))),
 ('Width', (Attr'Width':7.43(float))),
 ('name', (Attr'name':MedMnSteel_10mps_1_RD(str))),
 ('orientation', (Attr'orientation':RD(str))),
 ('sdata_date', (Attr'sdata_date':2020-12-10T00:00:00+00:00(str))),
 ('sdata_version', (Attr'sdata_version':0.10.1(str))),
 ('uuid', (Attr'uuid':2b8fe212a41a30a4955f869cfdde046c(str)))]

In [20]:
data.table

,Time (s),Extension (mm),Load (kN),Engineering Strain,Engineering Stress (MPa),True Strain,True Stress (MPa)
index,,,,,,,
0,0.00000,0.000000,-0.346456,0.000000,-31.51045,0.000000,-31.510450
1,0.00005,0.000138,-0.309855,0.000008,-44.92826,0.000008,-44.928624
2,0.00010,0.001084,-0.329818,0.000064,-35.57331,0.000064,-35.575577
3,0.00015,0.006859,-0.140176,0.000403,-9.35123,0.000403,-9.355002
4,0.00020,0.008749,0.531880,0.000515,52.44761,0.000514,52.474598
5,0.00025,0.017484,1.337015,0.001028,137.66427,0.001028,137.805827
6,0.00030,0.032535,2.448243,0.001913,272.66403,0.001912,273.185770
7,0.00035,0.059019,4.720592,0.003471,542.04902,0.003465,543.930526
8,0.00040,0.182078,8.027641,0.010708,819.27482,0.010652,828.048024
9,0.00045,0.559806,8.583270,0.032924,901.48198,0.032393,931.162192
10,0.00050,1.056680,7.485329,0.062146,864.39066,0.060292,918.109255
11,0.00055,1.535190,8.290489,0.090289,853.68431,0.086443,930.762698
12,0.00060,1.952340,8.223929,0.114822,910.72353,0.108695,1015.294627
13,0.00065,2.459370,8.732949,0.144642,916.67848,0.135092,1049.268689
14,0.00070,2.966730,8.530002,0.174481,937.87568,0.160826,1101.517167
15,0.00075,3.492380,8.886013,0.205396,947.03726,0.186808,1141.554925
16,0.00080,4.021580,8.965859,0.236520,967.45605,0.212301,1196.278755
17,0.00085,4.557640,8.989139,0.268048,966.98613,0.237479,1226.184828
18,0.00090,5.064910,8.949249,0.297882,965.57341,0.260734,1253.200349
19,0.00095,5.595900,8.935896,0.329111,961.49926,0.284510,1277.939243
20,0.00100,6.158470,8.822788,0.362197,947.87483,0.309099,1291.192250
21,0.00105,6.743820,8.553302,0.396623,924.77565,0.334057,1291.562943
22,0.00110,7.485980,8.297153,0.440271,891.80190,0.364831,1284.436414

In [21]:
data.refactor()
data.df.head()

,Time,Extension,Load,Engineering Strain,Engineering Stress,True Strain,True Stress
index,,,,,,,
0,0.00000,0.000000,-0.346456,0.000000,-31.51045,0.000000,-31.510450
1,0.00005,0.000138,-0.309855,0.000008,-44.92826,0.000008,-44.928624
2,0.00010,0.001084,-0.329818,0.000064,-35.57331,0.000064,-35.575577
3,0.00015,0.006859,-0.140176,0.000403,-9.35123,0.000403,-9.355002
4,0.00020,0.008749,0.531880,0.000515,52.44761,0.000514,52.474598

In [22]:
data.metadata.df

,name,value,dtype,unit,description,label
key,,,,,,
Gauge Length,Gauge Length,20,float,mm,,
License,License,Creative Commons Lizenz,str,-,,
Material,Material,Med Mn Steel,str,,,
Source,Source,https://materialsdata.nist.gov/handle/11256/823,str,-,,
Target Strain Rate,Target Strain Rate,500,float,1/s,,
Test Name,Test Name,10mps(1),str,,,
Thickness,Thickness,1.25,float,mm,,
Width,Width,7.43,float,mm,,
name,name,MedMnSteel_10mps_1_RD,str,-,,10mps(1)-RD
orientation,orientation,RD,str,,,
sdata_date,sdata_date,2020-12-10T00:00:00+00:00,str,-,,
sdata_version,sdata_version,0.10.1,str,,,
uuid,uuid,2b8fe212a41a30a4955f869cfdde046c,str,-,,
Time,Time,NaN,float,s,,Time (s)
Extension,Extension,NaN,float,mm,,Extension (mm)
Load,Load,NaN,float,kN,,Load (kN)
Engineering Strain,Engineering Strain,NaN,float,,,Engineering Strain
Engineering Stress,Engineering Stress,NaN,float,MPa,,Engineering Stress (MPa)
True Strain,True Strain,NaN,float,,,True Strain
True Stress,True Stress,NaN,float,MPa,,True Stress (MPa)