In [20]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%autosave 0
    
import logging
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

import os
import sys
import numpy as np
import pandas as pd
import sdata
import uuid
import time
from sdata import Data
from sdata.iolib.vault import FileSystemVault
from sdata.iolib.hdf import FlatHDFDataStore
print("sdata v{}".format(sdata.__version__))
from sdata.contrib.simple_graph import database

11:35:24 DEBUG:Loaded backend module://ipykernel.pylab.backend_inline version unknown.

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Autosave disabled
sdata v0.17.0

In [2]:
import shutil
shutil.rmtree("/tmp/sdatavault")

In [3]:
vault = FileSystemVault("/tmp/sdatavault")
vault.index.df

11:09:07 INFO:create/open vault /tmp/sdatavault

Empty DataFrame
Columns: [!sdata_version, !sdata_name, !sdata_uuid, !sdata_class, !sdata_parent, !sdata_project, !sdata_ctime, !sdata_mtime]
Index: []

In [4]:
vault

(FileSystemVault:/tmp/sdatavault)

In [5]:
data = sdata.Data(name="otto", 
                  uuid=sdata.uuid_from_str("otto"), 
                  table=pd.DataFrame({"a":[1,2,3]}),
                  description="Hallo\nSpencer",
                  project="P1")
data.metadata.add("a", 1)
datac = data.copy()
datac.uuid = '2689e23926874382b10b95e0f1cd90eb'
data2 = sdata.Data(name="karl", 
                   uuid=sdata.uuid_from_str("karl"))
data, datac, data2

((Data 'otto':21b83703d98e38a7be2e50e38326d0ce),
 (Data 'otto':2689e23926874382b10b95e0f1cd90eb),
 (Data 'karl':df26fe1945b93a149ee710e8fa887b2e))

In [6]:
data.metadata.get_sdict()

{'!sdata_class': 'Data',
 '!sdata_ctime': '2021-01-17T23:09:09.607403+00:00',
 '!sdata_mtime': '2021-01-17T23:09:09.607670+00:00',
 '!sdata_name': 'otto',
 '!sdata_parent': '',
 '!sdata_project': 'P1',
 '!sdata_uuid': '21b83703d98e38a7be2e50e38326d0ce',
 '!sdata_version': '0.17.0'}

In [7]:
vault.dump_blob(data)

11:09:11 INFO:dump blob /tmp/sdatavault/objects/21/ce/
11:09:11 INFO:NumExpr defaulting to 8 threads.
/home/ingolf.lepenies/anaconda3/envs/sfem3/lib/python3.7/site-packages/ipykernel_launcher.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['name', 'value', 'dtype', 'unit', 'description', 'label'], dtype='object')]

  """Entry point for launching an IPython kernel.

In [8]:
vault.index.df

,!sdata_version,!sdata_name,!sdata_uuid,!sdata_class,!sdata_parent,!sdata_project,!sdata_ctime,!sdata_mtime
21b83703d98e38a7be2e50e38326d0ce,0.17.0,otto,21b83703d98e38a7be2e50e38326d0ce,Data,,P1,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.607670+00:00

In [9]:
vault.dump_blob(data2)
vault.dump_blob(datac)

11:09:14 INFO:dump blob /tmp/sdatavault/objects/df/2e/
11:09:14 INFO:dump blob /tmp/sdatavault/objects/26/eb/
/home/ingolf.lepenies/anaconda3/envs/sfem3/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['name', 'value', 'dtype', 'unit', 'description', 'label'], dtype='object')]

In [10]:
vault.dump_hdf5_index()
vault.index.df

,!sdata_version,!sdata_name,!sdata_uuid,!sdata_class,!sdata_parent,!sdata_project,!sdata_ctime,!sdata_mtime
21b83703d98e38a7be2e50e38326d0ce,0.17.0,otto,21b83703d98e38a7be2e50e38326d0ce,Data,,P1,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.607670+00:00
df26fe1945b93a149ee710e8fa887b2e,0.17.0,karl,df26fe1945b93a149ee710e8fa887b2e,Data,,,2021-01-17T23:09:09.610965+00:00,2021-01-17T23:09:09.611163+00:00
2689e23926874382b10b95e0f1cd90eb,0.17.0,otto,2689e23926874382b10b95e0f1cd90eb,Data,21b83703d98e38a7be2e50e38326d0ce,P1,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.609884+00:00

In [11]:
vault2 = FileSystemVault("/tmp/sdatavault")
vault2.index.df

11:09:17 INFO:create/open vault /tmp/sdatavault
11:09:17 DEBUG:load vault index /tmp/sdatavault

,!sdata_version,!sdata_name,!sdata_uuid,!sdata_class,!sdata_parent,!sdata_project,!sdata_ctime,!sdata_mtime
21b83703d98e38a7be2e50e38326d0ce,0.17.0,otto,21b83703d98e38a7be2e50e38326d0ce,Data,,P1,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.607670+00:00
df26fe1945b93a149ee710e8fa887b2e,0.17.0,karl,df26fe1945b93a149ee710e8fa887b2e,Data,,,2021-01-17T23:09:09.610965+00:00,2021-01-17T23:09:09.611163+00:00
2689e23926874382b10b95e0f1cd90eb,0.17.0,otto,2689e23926874382b10b95e0f1cd90eb,Data,21b83703d98e38a7be2e50e38326d0ce,P1,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.609884+00:00

In [12]:
vault.reindex()
vault.index.df

11:09:32 INFO:get blob metadata /tmp/sdatavault/objects/26/eb/
11:09:32 INFO:get blob metadata /tmp/sdatavault/objects/21/ce/
11:09:32 INFO:get blob metadata /tmp/sdatavault/objects/df/2e/

key,!sdata_class,!sdata_ctime,!sdata_mtime,!sdata_name,!sdata_parent,!sdata_project,!sdata_uuid,!sdata_version
2689e23926874382b10b95e0f1cd90eb,Data,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.609884+00:00,otto,21b83703d98e38a7be2e50e38326d0ce,P1,2689e23926874382b10b95e0f1cd90eb,0.17.0
21b83703d98e38a7be2e50e38326d0ce,Data,2021-01-17T23:09:09.607403+00:00,2021-01-17T23:09:09.607670+00:00,otto,,P1,21b83703d98e38a7be2e50e38326d0ce,0.17.0
df26fe1945b93a149ee710e8fa887b2e,Data,2021-01-17T23:09:09.610965+00:00,2021-01-17T23:09:09.611163+00:00,karl,,,df26fe1945b93a149ee710e8fa887b2e,0.17.0

In [13]:
df = vault.index.df[[Data.SDATA_NAME]]
list(df.drop_duplicates().iloc[:,0])

['otto', 'karl']

In [14]:
vault.index.get_names()

['karl', 'otto']

In [11]:
vault.get_blob_by_name("otto")

10:40:28 DEBUG:get_blob_by_name: load 2689e23926874382b10b95e0f1cd90eb
10:40:28 INFO:load blob /tmp/sdatavault/objects/26/eb/
10:40:28 DEBUG:get_blob_by_name: load 21b83703d98e38a7be2e50e38326d0ce
10:40:28 INFO:load blob /tmp/sdatavault/objects/21/ce/

df_selected 2

[(Data 'otto':2689e23926874382b10b95e0f1cd90eb),
 (Data 'otto':21b83703d98e38a7be2e50e38326d0ce)]

In [12]:
vault.load_blob_metadata_value_df('21b83703d98e38a7be2e50e38326d0ce')

10:40:29 INFO:get blob metadata /tmp/sdatavault/objects/21/ce/

key,!sdata_class,!sdata_ctime,!sdata_mtime,!sdata_name,!sdata_parent,!sdata_project,!sdata_uuid,!sdata_version
21b83703d98e38a7be2e50e38326d0ce,Data,2021-01-17T22:40:28.025162+00:00,2021-01-17T22:40:28.025318+00:00,otto,,P1,21b83703d98e38a7be2e50e38326d0ce,0.17.0

In [13]:
data_ = vault.load_blob('21b83703d98e38a7be2e50e38326d0ce')
print(data_)
data==data_

10:40:29 INFO:load blob /tmp/sdatavault/objects/21/ce/

(Data 'otto':21b83703d98e38a7be2e50e38326d0ce)

False

In [14]:
data2_ = vault.load_blob('df26fe1945b93a149ee710e8fa887b2e')
print(data2_)
data2==data2_

10:40:29 INFO:load blob /tmp/sdatavault/objects/df/2e/

(Data 'karl':df26fe1945b93a149ee710e8fa887b2e)

False

In [15]:
vault.keys()

['2689e23926874382b10b95e0f1cd90eb',
 '21b83703d98e38a7be2e50e38326d0ce',
 'df26fe1945b93a149ee710e8fa887b2e']

In [16]:
metadata = vault.load_blob_metadata('21b83703d98e38a7be2e50e38326d0ce')
metadata.df

10:40:29 INFO:get blob metadata /tmp/sdatavault/objects/21/ce/

,name,value,dtype,unit,description,label,required
key,,,,,,,
!sdata_class,!sdata_class,Data,str,-,sdata class,,False
!sdata_ctime,!sdata_ctime,2021-01-17T22:40:28.025162+00:00,str,-,creation date,,False
!sdata_mtime,!sdata_mtime,2021-01-17T22:40:28.025318+00:00,str,-,modification date,,False
!sdata_name,!sdata_name,otto,str,-,name of the data object,,False
!sdata_parent,!sdata_parent,,str,-,uuid of the parent sdata object,,False
!sdata_project,!sdata_project,P1,str,-,,,False
!sdata_uuid,!sdata_uuid,21b83703d98e38a7be2e50e38326d0ce,str,-,Universally Unique Identifier,,False
!sdata_version,!sdata_version,0.17.0,str,-,sdata package version,,False
a,a,1,int,-,,,False

In [17]:
m = metadata.sdf[["name", "value"]]
m

                          name                             value
key
!sdata_class      !sdata_class                              Data
!sdata_ctime      !sdata_ctime  2021-01-17T22:40:28.025162+00:00
!sdata_mtime      !sdata_mtime  2021-01-17T22:40:28.025318+00:00
!sdata_name        !sdata_name                              otto
!sdata_parent    !sdata_parent
!sdata_project  !sdata_project                                P1
!sdata_uuid        !sdata_uuid  21b83703d98e38a7be2e50e38326d0ce
!sdata_version  !sdata_version                            0.17.0

In [18]:
mt = metadata.df[["value"]].transpose(copy=True)
mt

key,!sdata_class,!sdata_ctime,!sdata_mtime,!sdata_name,!sdata_parent,!sdata_project,!sdata_uuid,!sdata_version,a
value,Data,2021-01-17T22:40:28.025162+00:00,2021-01-17T22:40:28.025318+00:00,otto,,P1,21b83703d98e38a7be2e50e38326d0ce,0.17.0,1

In [19]:
mt.index.values

array(['value'], dtype=object)

In [20]:
mt.index = [metadata.get(sdata.Data.SDATA_UUID).value]
mt.index.values

array(['21b83703d98e38a7be2e50e38326d0ce'], dtype=object)

In [21]:
mt.index = np.array([metadata.get(sdata.Data.SDATA_UUID).value]*len(mt))
mt

key,!sdata_class,!sdata_ctime,!sdata_mtime,!sdata_name,!sdata_parent,!sdata_project,!sdata_uuid,!sdata_version,a
21b83703d98e38a7be2e50e38326d0ce,Data,2021-01-17T22:40:28.025162+00:00,2021-01-17T22:40:28.025318+00:00,otto,,P1,21b83703d98e38a7be2e50e38326d0ce,0.17.0,1

In [22]:
print(mt)

key                              !sdata_class  \
21b83703d98e38a7be2e50e38326d0ce         Data

key                                                   !sdata_ctime  \
21b83703d98e38a7be2e50e38326d0ce  2021-01-17T22:40:28.025162+00:00

key                                                   !sdata_mtime  \
21b83703d98e38a7be2e50e38326d0ce  2021-01-17T22:40:28.025318+00:00

key                              !sdata_name !sdata_parent !sdata_project  \
21b83703d98e38a7be2e50e38326d0ce        otto                           P1

key                                                    !sdata_uuid  \
21b83703d98e38a7be2e50e38326d0ce  21b83703d98e38a7be2e50e38326d0ce

key                              !sdata_version  a
21b83703d98e38a7be2e50e38326d0ce         0.17.0  1

In [23]:
["abc"]*len(mt)

['abc']

In [24]:
data.metadata.udf

    name  value dtype unit description label  required
key
a      a      1   int    -                       False

In [25]:
data.metadata.sdf

,name,value,dtype,unit,description,label,required
key,,,,,,,
!sdata_class,!sdata_class,Data,str,-,sdata class,,False
!sdata_ctime,!sdata_ctime,2021-01-17T22:40:28.025162+00:00,str,-,creation date,,False
!sdata_mtime,!sdata_mtime,2021-01-17T22:40:28.025318+00:00,str,-,modification date,,False
!sdata_name,!sdata_name,otto,str,-,name of the data object,,False
!sdata_parent,!sdata_parent,,str,-,uuid of the parent sdata object,,False
!sdata_project,!sdata_project,P1,str,-,,,False
!sdata_uuid,!sdata_uuid,21b83703d98e38a7be2e50e38326d0ce,str,-,Universally Unique Identifier,,False
!sdata_version,!sdata_version,0.17.0,str,-,sdata package version,,False

In [26]:
data.metadata.df

,name,value,dtype,unit,description,label,required
key,,,,,,,
!sdata_class,!sdata_class,Data,str,-,sdata class,,False
!sdata_ctime,!sdata_ctime,2021-01-17T22:40:28.025162+00:00,str,-,creation date,,False
!sdata_mtime,!sdata_mtime,2021-01-17T22:40:28.025318+00:00,str,-,modification date,,False
!sdata_name,!sdata_name,otto,str,-,name of the data object,,False
!sdata_parent,!sdata_parent,,str,-,uuid of the parent sdata object,,False
!sdata_project,!sdata_project,P1,str,-,,,False
!sdata_uuid,!sdata_uuid,21b83703d98e38a7be2e50e38326d0ce,str,-,Universally Unique Identifier,,False
!sdata_version,!sdata_version,0.17.0,str,-,sdata package version,,False
a,a,1,int,-,,,False

In [27]:
datac = data.copy()
datac.name = "otto2"
datac.uuid = 'b8315be85d9945579cf8dc6a80a62524'
datac.df["b"] = datac.df["a"]**2
datac.df
datac.metadata.add("force", 1.23, dtype="float", description="a force", label="F")
datac.metadata.add("runid", 123, dtype="int", description="a int", label="r")
datac

(Data 'otto2':b8315be85d9945579cf8dc6a80a62524)

In [28]:
data2 = va.get_data_by_uuid('b8315be85d9945579cf8dc6a80a62524')
print(data2)
data2.metadata.df
print([data2.description])
(data2.describe())

NameError: name 'va' is not defined

In [18]:
import sqlite3
sqlite3.version

'2.6.0'

In [19]:
import sys
sys.version

'3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]'